from dataclasses import dataclass

# THIS FILE IS AUTO-GENERATED BY config/update_config_files.py, DO NOT EDIT MANUALLY!


@dataclass
class InSilicoData:
    lane_id: str  # mandatory; contains illegal characters
    public_name: str  # mandatory; contains illegal characters
    sample: str  # mandatory; must not contain illegal characters
    ERR: str  # optional; must be a ERR accession number (ERR# format)
    ERS: str  # optional; must be a ERS accession number (ERS# format)
    no_of_genome: str  # optional
    duplicate: str  # optional
    Paper_1: str  # optional
    In_Silico_St: str  # optional; must be an integer (1-5 digits), 'UNDETERMINABLE', 'NEW', 'FAILED' or '_'
    aroE: str  # optional; must be an integer (1-3 digits), 'UNDETERMINABLE', 'NEW', 'FAILED' or '_'
    gdh: str  # optional; must be an integer (1-3 digits), 'UNDETERMINABLE', 'NEW', 'FAILED' or '_'
    gki: str  # optional; must be an integer (1-3 digits), 'UNDETERMINABLE', 'NEW', 'FAILED' or '_'
    recP: str  # optional; must be an integer (1-3 digits), 'UNDETERMINABLE', 'NEW', 'FAILED' or '_'
    spi: str  # optional; must be an integer (1-3 digits), 'UNDETERMINABLE', 'NEW', 'FAILED' or '_'
    xpt: str  # optional; must be an integer (1-3 digits), 'UNDETERMINABLE', 'NEW', 'FAILED' or '_'
    ddl: str  # optional; must be an integer (1-4 digits), 'UNDETERMINABLE', 'NEW', 'FAILED' or '_'
    country: str  # optional
    Continent: str  # optional
    Manifest_type: str  # optional
    children_under_5yrs: str  # optional
    GPSC: str  # optional; must be an integer (1-4 digits), or '_'
    GPSC__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    In_silico_serotype: str  # optional
    In_silico_serotype__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    pbp1a: str  # optional; should be a valid 1 to 3 digit number; can be 'NEW' or 'NF'
    pbp2b: str  # optional; should be a valid 1 to 3 digit number; can be 'NEW' or 'NF'
    pbp2x: str  # optional; should be a valid 1 to 3 digit number; can be 'NEW', 'ERROR' or 'NF'
    WGS_PEN: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF'
    WGS_PEN_SIR_Meningitis: str  # optional
    WGS_PEN_SIR_Nonmeningitis: str  # optional
    WGS_AMO: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF'
    WGS_AMO_SIR: str  # optional
    WGS_MER: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF'
    WGS_MER_SIR: str  # optional
    WGS_TAX: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF'
    WGS_TAX_SIR_Meningitis: str  # optional
    WGS_TAX_SIR_Nonmeningitis: str  # optional
    WGS_CFT: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF'
    WGS_CFT_SIR_Meningitis: str  # optional
    WGS_CFT_SIR_Nonmeningitis: str  # optional
    WGS_CFX: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF'
    WGS_CFX_SIR: str  # optional
    WGS_ERY: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF' or 'FLAG'
    WGS_ERY_SIR: str  # optional
    WGS_CLI: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF' or 'FLAG'
    WGS_CLI_SIR: str  # optional
    WGS_SYN: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF' or 'FLAG'
    WGS_SYN_SIR: str  # optional
    WGS_LZO: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF' or 'FLAG'
    WGS_LZO_SIR: str  # optional
    WGS_ERY_CLI: str  # optional
    WGS_COT: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF' or 'FLAG'
    WGS_COT_SIR: str  # optional
    WGS_TET: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF' or 'FLAG'
    WGS_TET_SIR: str  # optional
    WGS_DOX: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF' or 'FLAG'
    WGS_DOX_SIR: str  # optional
    WGS_LFX: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF' or 'FLAG'
    WGS_LFX_SIR: str  # optional
    WGS_CHL: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF' or 'FLAG'
    WGS_CHL_SIR: str  # optional
    WGS_RIF: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF' or 'FLAG'
    WGS_RIF_SIR: str  # optional
    WGS_VAN: str  # optional; can be an integer or decimal; can bee preceeded by '<', '>', '<=' or '>='; can be 'NF' or 'FLAG'
    WGS_VAN_SIR: str  # optional
    EC: str  # optional
    Cot: str  # optional
    Tet__autocolour: str  # optional
    FQ__autocolour: str  # optional
    Other: str  # optional
    PBP1A_2B_2X__autocolour: str  # optional
    WGS_PEN_SIR_Meningitis__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_PEN_SIR_Nonmeningitis__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_AMO_SIR__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_MER_SIR__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_TAX_SIR_Meningitis__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_TAX_SIR_Nonmeningitis__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_CFT_SIR_Meningitis__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_CFT_SIR_Nonmeningitis__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_CFX_SIR__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_ERY_SIR__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_CLI_SIR__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_SYN_SIR__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_LZO_SIR__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_COT_SIR__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_TET_SIR__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_DOX_SIR__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_LFX_SIR__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_CHL_SIR__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_RIF_SIR__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    WGS_VAN_SIR__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    ermB: str  # optional
    ermB__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    mefA: str  # optional
    mefA__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    folA_I100L: str  # optional
    folA_I100L__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    folP__autocolour: str  # optional
    cat: str  # optional
    cat__colour: str  # optional; should be an hex colour code (format #000000), '#NA', '_' or 'transparent'
    PCV7: str  # optional
    PCV10: str  # optional
    PCV13: str  # optional
    PCV15: str  # optional
    PCV20: str  # optional
    Pneumosil: str  # optional
    Published: str  # optional
