from dataclasses import dataclass

# THIS FILE IS AUTO-GENERATED BY config/update_config_files.py, DO NOT EDIT MANUALLY!


@dataclass
class InSilicoData:
    lane_id: str  # mandatory; contains illegal characters
    cps_type: str  # mandatory
    ST: str  # mandatory
    adhP: str  # mandatory
    pheS: str  # mandatory
    atr: str  # mandatory
    glnA: str  # mandatory
    sdhA: str  # mandatory
    glcK: str  # mandatory
    tkt: str  # mandatory
    twenty_three_S1: str  # mandatory; must be pos, neg or empty
    twenty_three_S3: str  # mandatory; must be pos, neg or empty
    AAC6APH2: str  # mandatory; must be pos, neg or empty
    AADECC: str  # mandatory; must be pos, neg or empty
    ANT6: str  # mandatory; must be pos, neg or empty
    APH3III: str  # mandatory; must be pos, neg or empty
    APH3OTHER: str  # mandatory; must be pos, neg or empty
    CATPC194: str  # mandatory; must be pos, neg or empty
    CATQ: str  # mandatory; must be pos, neg or empty
    ERMA: str  # mandatory; must be pos, neg or empty
    ERMB: str  # mandatory; must be pos, neg or empty
    ERMT: str  # mandatory; must be pos, neg or empty
    LNUB: str  # mandatory; must be pos, neg or empty
    LNUC: str  # mandatory; must be pos, neg or empty
    LSAC: str  # mandatory; must be pos, neg or empty
    MEFA: str  # mandatory; must be pos, neg or empty
    MPHC: str  # mandatory; must be pos, neg or empty
    MSRA: str  # mandatory; must be pos, neg or empty
    MSRD: str  # mandatory; must be pos, neg or empty
    FOSA: str  # mandatory; must be pos, neg or empty
    GYRA: str  # mandatory; must be pos, neg or empty
    PARC: str  # mandatory; must be pos, neg or empty
    RPOBGBS_1: str  # mandatory; must be pos, neg or empty
    RPOBGBS_2: str  # mandatory; must be pos, neg or empty
    RPOBGBS_3: str  # mandatory; must be pos, neg or empty
    RPOBGBS_4: str  # mandatory; must be pos, neg or empty
    SUL2: str  # mandatory; must be pos, neg or empty
    TETB: str  # mandatory; must be pos, neg or empty
    TETL: str  # mandatory; must be pos, neg or empty
    TETM: str  # mandatory; must be pos, neg or empty
    TETO: str  # mandatory; must be pos, neg or empty
    TETS: str  # mandatory; must be pos, neg or empty
    ALP1: str  # mandatory; must be pos, neg or empty
    ALP23: str  # mandatory; must be pos, neg or empty
    ALPHA: str  # mandatory; must be pos, neg or empty
    HVGA: str  # mandatory; must be pos, neg or empty
    PI1: str  # mandatory; must be pos, neg or empty
    PI2A1: str  # mandatory; must be pos, neg or empty
    PI2A2: str  # mandatory; must be pos, neg or empty
    PI2B: str  # mandatory; must be pos, neg or empty
    RIB: str  # mandatory; must be pos, neg or empty
    SRR1: str  # mandatory; must be pos, neg or empty
    SRR2: str  # mandatory; must be pos, neg or empty
    twenty_three_S1_variant: str  # mandatory; must contain comma-separated variants (e.g. T78Q,L55A) or empty value
    twenty_three_S3_variant: str  # mandatory; must contain comma-separated variants (e.g. T78Q,L55A) or empty value
    GYRA_variant: str  # mandatory; must contain comma-separated variants (e.g. T78Q,L55A) or empty value
    PARC_variant: str  # mandatory; must contain comma-separated variants (e.g. T78Q,L55A) or empty value
    RPOBGBS_1_variant: str  # mandatory; must contain comma-separated variants (e.g. T78Q,L55A) or empty value
    RPOBGBS_2_variant: str  # mandatory; must contain comma-separated variants (e.g. T78Q,L55A) or empty value
    RPOBGBS_3_variant: str  # mandatory; must contain comma-separated variants (e.g. T78Q,L55A) or empty value
    RPOBGBS_4_variant: str  # mandatory; must contain comma-separated variants (e.g. T78Q,L55A) or empty value
