from dataclasses import dataclass

# THIS FILE IS AUTO-GENERATED BY update_config_files.py, DO NOT EDIT MANUALLY!


@dataclass
class Metadata:
    sanger_sample_id: str  # mandatory; must not contain illegal characters
    sample_name: str  # mandatory; contains illegal characters
    public_name: str  # mandatory; contains illegal characters
    study_name: str  # optional; contains illegal characters
    submitting_institution: str  # mandatory
    selection_random: str  # optional
    continent: str  # optional
    country: str  # optional
    region: str  # optional
    city: str  # optional
    facility_where_collected: str  # optional
    month_collection: str  # optional
    year_collection: str  # optional; must be a YYYY format year
    gender: str  # optional
    age_years: str  # optional; should be an integer; can be a decimal number; can include spaces; can include '>','<', '=', '&' symbols
    age_months: str  # optional; should be an integer; can be a decimal (max 2 decimals)
    age_days: str  # optional; should be an integer
    clinical_manifestation: str  # optional
    source: str  # optional
    HIV_status: str  # optional
    underlying_conditions: str  # optional
    phenotypic_serotype_method: str  # optional
    phenotypic_serotype: str  # optional; contains illegal characters
    sequence_type: str  # optional; contains illegal characters
    aroE: str  # optional; must be an integer (max 3 digits)
    gdh: str  # optional; must be an integer (max 3 digits)
    gki: str  # optional; must be an integer (max 3 digits)
    recP: str  # optional; must be an integer (max 3 digits)
    spi: str  # optional; must be an integer (max 3 digits), 'UNKNOWN'
    xpt: str  # optional; must be an integer (max 3 digits)
    ddl: str  # optional; must be an integer (max 3 digits)
    AST_method_penicillin: str  # optional
    penicillin: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS
    AST_method_amoxicillin: str  # optional
    amoxicillin: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS
    AST_method_cefotaxime: str  # optional
    cefotaxime: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS or '_'
    AST_method_ceftriaxone: str  # optional
    ceftriaxone: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS
    AST_method_cefuroxime: str  # optional
    cefuroxime: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS
    AST_method_meropenem: str  # optional
    meropenem: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS
    AST_method_erythromycin: str  # optional
    erythromycin: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS
    AST_method_clindamycin: str  # optional
    clindamycin: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS
    AST_method_trim_sulfa: str  # optional
    trim_sulfa: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS
    AST_method_vancomycin: str  # optional
    vancomycin: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS
    AST_method_linezolid: str  # optional
    linezolid: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS
    AST_method_ciprofloxacin: str  # optional
    ciprofloxacin: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS
    AST_method_chloramphenicol: str  # optional
    chloramphenicol: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS
    AST_method_tetracycline: str  # optional
    tetracycline: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS
    AST_method_levofloxacin: str  # optional
    levofloxacin: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS
    AST_method_synercid: str  # optional
    synercid: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS
    AST_method_rifampin: str  # optional
    rifampin: str  # optional; should be a valid floating point number; can start with '>','<', '>=' or '<=' and optionally end with units "mm" or "µg/ml" ('u' permitted in place of 'µ'); or alternatively S, I, R or NS
    comments: str  # optional
    latitude: float  # optional; must be a number between -180 and 180, with up to 8 decimal places
    longitude: float  # optional; must be a number between -180 and 180, with up to 8 decimal places
    resolution: str  # optional; must be an integer (range 0-2)
    vaccine_period: str  # optional; should be 'PREPCV', 'POSTPCV#-#YR'
    intro_year: str  # optional; must be a YYYY format year
    PCV_type: str  # optional; should start with 'PCV' followed by a number
