from dataclasses import dataclass

# THIS FILE IS AUTO-GENERATED BY update_config_files.py, DO NOT EDIT MANUALLY!


@dataclass
class QCData:
    lane_id: str  # mandatory; contains illegal characters
    qc: str  # optional
    Streptococcus_pneumoniae: str  # optional; must be a number between 0-100 (1 or 2 decimal places are allowed)
    total_length: str  # optional; must be an 1-10 digits number (integer)
    No_contigs: str  # optional; must be a 1-5 digits number (integer)
    genome_covered: str  # optional; must be a number between 0-100 (1 or 2 decimal places are allowed)
    depth_of_coverage: str  # optional; must be a number between 0-2000 (1 or 2 decimal places are allowed)
    Proportion_of_Het_SNPs: str  # optional; must be a number between 0-100 (1 or 2 decimal places are allowed)
    supplier_name: str  # mandatory; contains illegal characters
    Hetsites_50bp: str  # optional; must be an integer between 0-5000
