from dataclasses import dataclass

# THIS FILE IS AUTO-GENERATED BY config/update_config_files.py, DO NOT EDIT MANUALLY!


@dataclass
class QCData:
    lane_id: str  # mandatory; contains illegal characters
    sample_name: str  # mandatory; must not contain illegal characters
    sample_accession: str  # mandatory; must be a ERS accession number (ERS# format)
    lane_accession: str  # mandatory; must be a ERR accession number (ERR# format)
    supplier_name: str  # mandatory; contains illegal characters
    public_name: str  # mandatory; contains illegal characters
    Streptococcus_pneumoniae: str  # optional; must be a number between 0-100 (1 or 2 decimal places are needed)
    total_length: str  # optional; must be an integer (whole number)
    No_contigs: str  # optional; must be an integer (whole number)
    genome_covered: str  # optional; must be a number between 0-100 (1 or 2 decimal places are needed)
    depth_of_coverage: str  # optional; must be a number between 0-2000 (1 or 2 decimal places are needed);
    X_Het_SNPs_Total_No_of_SNPs: str  # optional; must be a number between 0-100 (1 or 2 decimal places are needed); can be 'NA'
    qc: str  # optional
    Hetsites_50bp: str  # optional; must be a max 4 digits number or '#N/A'
