from dataclasses import dataclass

# THIS FILE IS AUTO-GENERATED BY config/update_config_files.py, DO NOT EDIT MANUALLY!


@dataclass
class InSilicoData:
    lane_id: str  # mandatory; contains illegal characters
    cps_type: str  # optional; must be a roman number (1-39); can be followed by a single lower case letter; can be 'NT'
    ST: str  # optional; must be an integer (max 4 digits) or `NF`; both can be followed by '*'
    adhP: str  # optional; must be an integer (max 3 digits), which can be followed by '*'; can be '-'
    pheS: str  # optional; must be an integer (max 3 digits), which can be followed by '*'; can be '-'
    atr: str  # optional; must be an integer (max 3 digits), which can be followed by '*'; can be '-'
    glnA: str  # optional; must be an integer (max 3 digits), which can be followed by '*'; can be '-'
    sdhA: str  # optional; must be an integer (max 3 digits), which can be followed by '*'; can be '-'
    glcK: str  # optional; must be an integer (max 3 digits), which can be followed by '*'; can be '-'
    tkt: str  # optional; must be an integer (max 3 digits), which can be followed by '*'; can be '-'
    AAC6APH2: str  # optional
    ANT6IA: str  # optional
    APH3III: str  # optional
    AADE: str  # optional
    CATPC194: str  # optional
    CATQ: str  # optional
    ERMA: str  # optional
    ERMB: str  # optional
    ERMT: str  # optional
    LNUB: str  # optional
    LNUC: str  # optional
    LSAC: str  # optional
    LSAE: str  # optional
    MEFA: str  # optional
    MSRD: str  # optional
    TETB: str  # optional
    TETL: str  # optional
    TETM: str  # optional
    TETW: str  # optional
    TETO: str  # optional
    TETS: str  # optional
    TETO32O: str  # optional
    TETOW: str  # optional
    TETOW32O: str  # optional
    TETOW32OWO: str  # optional
    TETOWO: str  # optional
    TETSM: str  # optional
    TETW32O: str  # optional
    ALP1: str  # optional
    ALP23: str  # optional
    ALPHA: str  # optional
    HVGA: str  # optional
    PI1: str  # optional
    PI2A1: str  # optional
    PI2A2: str  # optional
    PI2B: str  # optional
    RIB: str  # optional
    SRR1: str  # optional
    SRR2: str  # optional
    twenty_three_S1_variant: str  # optional; must follow a valid variant format (e.g. 'L55A' or 'G8A'); can be empty
    twenty_three_S3_variant: str  # optional; must follow a valid variant format (e.g. 'L55A' or 'G8A'); can be empty
    GYRA_variant: str  # optional; must follow a valid variant format (e.g. 'L55A' or 'G8A'); can be empty
    PARC_variant: str  # optional; must follow a valid variant format (e.g. 'L55A' or 'G8A'); can be empty
    TYPER_PIPELINE_VERSION: str  # mandatory; must follow a valid format (e.g. v1.0.0)
