from dataclasses import dataclass

# THIS FILE IS AUTO-GENERATED BY update_config_files.py, DO NOT EDIT MANUALLY!


@dataclass
class InSilicoData:
    lane_id: str  # mandatory; contains illegal characters
    cps_type: str  # optional; must be a roman number (1-39); can be followed by a single lower case letter; can be "NT" or empty
    ST: str  # optional; must be a positive integer (max 4 digits) or "NF"; can be followed by "*", "?" or both; can be empty
    adhP: str  # optional; must be a positive integer (max 3 digits), which can be followed by "*", "?" or both; can be "-" or empty
    pheS: str  # optional; must be a positive integer (max 3 digits), which can be followed by "*", "?" or both; can be "-" or empty
    atr: str  # optional; must be a positive integer (max 3 digits), which can be followed by "*", "?" or both; can be "-" or empty
    glnA: str  # optional; must be a positive integer (max 3 digits), which can be followed by "*", "?" or both; can be "-" or empty
    sdhA: str  # optional; must be a positive integer (max 3 digits), which can be followed by "*", "?" or both; can be "-" or empty
    glcK: str  # optional; must be a positive integer (max 3 digits), which can be followed by "*", "?" or both; can be "-" or empty
    tkt: str  # optional; must be a positive integer (max 3 digits), which can be followed by "*", "?" or both; can be "-" or empty
    AAC6APH2: str  # optional
    ANT6IA: str  # optional
    APH3III: str  # optional
    AADE: str  # optional
    CATPC194: str  # optional
    CATQ: str  # optional
    ERMA: str  # optional
    ERMB: str  # optional
    ERMT: str  # optional
    LNUB: str  # optional
    LNUC: str  # optional
    LSAC: str  # optional
    LSAE: str  # optional
    MEFA: str  # optional
    MSRD: str  # optional
    TETB: str  # optional
    TETL: str  # optional
    TETM: str  # optional
    TETW: str  # optional
    TETO: str  # optional
    TETS: str  # optional
    TETO32O: str  # optional
    TETOW: str  # optional
    TETOW32O: str  # optional
    TETOW32OWO: str  # optional
    TETOWO: str  # optional
    TETSM: str  # optional
    TETW32O: str  # optional
    ALP1: str  # optional
    ALP23: str  # optional
    ALPHA: str  # optional
    HVGA: str  # optional
    PI1: str  # optional
    PI2A1: str  # optional
    PI2A2: str  # optional
    PI2B: str  # optional
    RIB: str  # optional
    SRR1: str  # optional
    SRR2: str  # optional
    twenty_three_S1_variant: str  # optional; must contain one or multiple comma-separated variants (e.g. T78Q or T78Q,L55A), which can be followed by "*"; can be "*" or empty
    twenty_three_S3_variant: str  # optional; must contain one or multiple comma-separated variants (e.g. T78Q or T78Q,L55A), which can be followed by "*"; can be "*" or empty
    GYRA_variant: str  # optional; must contain one or multiple comma-separated variants (e.g. T78Q or T78Q,L55A), which can be followed by "*"; can be "*" or empty
    PARC_variant: str  # optional; must contain one or multiple comma-separated variants (e.g. T78Q or T78Q,L55A), which can be followed by "*"; can be "*" or empty
    TYPER_PIPELINE_VERSION: str  # mandatory; must follow a valid format (e.g. v1.0.0)
