from dataclasses import dataclass


# THIS FILE IS AUTO-GENERATED BY utils/update_metadata_files.py, DO NOT EDIT MANUALLY!

@dataclass
class QCData
    lane_id: str # mandatory; contains illegal characters
    rel_abun_sa: float # optional
