from dataclasses import dataclass

# THIS FILE IS AUTO-GENERATED BY config/update_config_files.py, DO NOT EDIT MANUALLY!


@dataclass
class QCData:
    lane_id: str  # mandatory; contains illegal characters
    rel_abun_sa: str  # optional
