stages:
  - formatting_and_linting_check
  - build
  - test
  - docker_tags_for_merges_and_releases


variables:
  DASH_API_CONTEXT:         "dash-api"
  # note there is no docker build associated with DATA_VIEW_CONTEXT
  DATA_VIEW_CONTEXT:        "data_view"
  METADATA_CONTEXT:         "metadata"
  FRONTEND_CONTEXT:         "frontend"
  QC_DATA_CONTEXT:          "qc-data"
  DOCKER_IMAGE_LIST:        "monocle-${DASH_API_CONTEXT} monocle-${METADATA_CONTEXT}-juno monocle-${METADATA_CONTEXT}-gps monocle-${FRONTEND_CONTEXT} monocle-proxy monocle-ldap-admin"
  DOCKER_COMMON_BUILD_ARGS: "--build-arg \"CACHE_BUST=$(date)\""
  DOCKER_IMAGE:             "${CI_REGISTRY_IMAGE}/docker:20"
  DOCKER_DIND_IMAGE:        "${CI_REGISTRY_IMAGE}/gitlab-ci-dind:latest"
  LINE_LENGTH:              120

Check that Python code is formatted & linted:
  stage: formatting_and_linting_check
  tags:
    - openstack-autoscale-theta
  # Keep this version in sync w/ the one from `./.pre-commit-config.yaml`.
  image: python:3.8.8-slim-buster
  before_script:
    # Install `git` needed for `isort` to ignore files from `.gitignore`
    - apt-get update && apt-get install -y git
    - pip install -r requirements-ci.txt
  script:
    - black --check --line-length ${LINE_LENGTH} . && isort --check-only . && flake8 || exit_code=$?
    - >
      if [[ $exit_code -eq 1 ]]; then
        echo "❌ Some Python code isn't formatted or linted. Ensure that you have `pre-commit` hooks insatlled locally (see the main README in `monocle` for details)."
      fi
    - exit $exit_code

Check that FE code & non-Python files are formatted & linted:
  stage: formatting_and_linting_check
  tags:
    - openstack-autoscale-theta
  # Keep this version in sync w/ the one from `./.pre-commit-config.yaml`.
  image: 16.15-alpine3.14
  before_script:
    # These version should match the ones from `./.pre-commit-config.yaml`:
    - npm i -g prettier@2.6.2 prettier-plugin-svelte@2.7.0 eslint@8.16.0 eslint-config-prettier@8.5.0 eslint-plugin-jest@26.4.5 eslint-plugin-svelte3@4.0.0
  script:
    # Keep these args in sync w/ Prettier & ESLint args in `./.gitlab-ci.yml` (besides `--write` & `--fix` respectively):
    - prettier --no-config --ignore-path .eslintignore && eslint || exit_code=$?
    - >
      if [[ $exit_code -eq 1 ]]; then
        echo "❌ Some FE code or non-Python files aren't formatted or linted. Ensure that you have `pre-commit` hooks insatlled locally (see the main README in `monocle` for details).
      fi
    - exit $exit_code

# at every git push, build docker images
# push the images to the container registry  with the commit SHA-1 as the tag
Dashboard API docker build:
  stage: build
  tags:
    - autoscale-large
  image: "${DOCKER_IMAGE}"
  services:
    - name:  "${DOCKER_DIND_IMAGE}"
      alias: docker
  variables:
    DOCKER_BUILDKIT:      1
    DOCKER_TLS_CERTDIR:   ""
    DOCKER_HOST:          "tcp://docker:2375"
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - >
         this_image="monocle-${DASH_API_CONTEXT}";
         cd "${CI_PROJECT_DIR}/${DASH_API_CONTEXT}";
         this_commit_tag="commit-${CI_COMMIT_SHORT_SHA}";
         echo "🐳 Building ${CI_REGISTRY_IMAGE}/${this_image}:${this_commit_tag} 🐳";
         docker pull $CI_REGISTRY_IMAGE/${this_image}:unstable || true;
         docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $CI_REGISTRY_IMAGE/${this_image}:unstable --tag $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag} ${DOCKER_COMMON_BUILD_ARGS} . ;
         echo "🐳 Pushing ${CI_REGISTRY_IMAGE}:${this_image}:${this_commit_tag} 🐳";
         docker push $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag};

Metadata API for JUNO docker build:
  stage: build
  tags:
    - autoscale-large
  image: "${DOCKER_IMAGE}"
  services:
    - name:  "${DOCKER_DIND_IMAGE}"
      alias: docker
  variables:
    DOCKER_BUILDKIT:      1
    DOCKER_TLS_CERTDIR:   ""
    DOCKER_HOST:          "tcp://docker:2375"
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - >
         this_project=juno
         this_image="monocle-${METADATA_CONTEXT}-${this_project}";
         cd "${CI_PROJECT_DIR}/${METADATA_CONTEXT}";
         this_commit_tag="commit-${CI_COMMIT_SHORT_SHA}";
         echo "🐳 Building ${CI_REGISTRY_IMAGE}/${this_image}:${this_commit_tag} 🐳";
         docker pull $CI_REGISTRY_IMAGE/${this_image}:unstable || true;
         docker build --build-arg PROJECT=${this_project} --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $CI_REGISTRY_IMAGE/${this_image}:unstable --tag $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag} ${DOCKER_COMMON_BUILD_ARGS} . ;
         echo "🐳 Pushing ${CI_REGISTRY_IMAGE}:${this_image}:${this_commit_tag} 🐳";
         docker push $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag};

Metadata API for GPS docker build:
  stage: build
  tags:
    - autoscale-large
  image: "${DOCKER_IMAGE}"
  services:
    - name:  "${DOCKER_DIND_IMAGE}"
      alias: docker
  variables:
    DOCKER_BUILDKIT:      1
    DOCKER_TLS_CERTDIR:   ""
    DOCKER_HOST:          "tcp://docker:2375"
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - >
         this_project=gps
         this_image="monocle-${METADATA_CONTEXT}-${this_project}";
         cd "${CI_PROJECT_DIR}/${METADATA_CONTEXT}";
         this_commit_tag="commit-${CI_COMMIT_SHORT_SHA}";
         echo "🐳 Building ${CI_REGISTRY_IMAGE}/${this_image}:${this_commit_tag} 🐳";
         docker pull $CI_REGISTRY_IMAGE/${this_image}:unstable || true;
         docker build --build-arg PROJECT=${this_project} --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $CI_REGISTRY_IMAGE/${this_image}:unstable --tag $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag} ${DOCKER_COMMON_BUILD_ARGS} . ;
         echo "🐳 Pushing ${CI_REGISTRY_IMAGE}:${this_image}:${this_commit_tag} 🐳";
         docker push $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag};

Front End docker build:
  stage: build
  tags:
    - autoscale-large
  image: "${DOCKER_IMAGE}"
  services:
    - name:  "${DOCKER_DIND_IMAGE}"
      alias: docker
  variables:
    DOCKER_BUILDKIT:      1
    DOCKER_TLS_CERTDIR:   ""
    DOCKER_HOST:          "tcp://docker:2375"
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - >
         this_image="monocle-${FRONTEND_CONTEXT}";
         cd "${CI_PROJECT_DIR}/${FRONTEND_CONTEXT}";
         this_commit_tag="commit-${CI_COMMIT_SHORT_SHA}";
         echo "🐳 Building ${CI_REGISTRY_IMAGE}/${this_image}:${this_commit_tag} 🐳";
         docker pull $CI_REGISTRY_IMAGE/${this_image}:unstable || true;
         docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $CI_REGISTRY_IMAGE/${this_image}:unstable --tag $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag} ${DOCKER_COMMON_BUILD_ARGS} . ;
         echo "🐳 Pushing ${CI_REGISTRY_IMAGE}:${this_image}:${this_commit_tag} 🐳";
         docker push $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag};

Proxy docker build:
  stage: build
  tags:
    - autoscale-large
  image: "${DOCKER_IMAGE}"
  services:
    - name:  "${DOCKER_DIND_IMAGE}"
      alias: docker
  variables:
    DOCKER_BUILDKIT:      1
    DOCKER_TLS_CERTDIR:   ""
    DOCKER_HOST:          "tcp://docker:2375"
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - >
         this_image="monocle-proxy";
         cd "${CI_PROJECT_DIR}/proxy";
         this_commit_tag="commit-${CI_COMMIT_SHORT_SHA}";
         echo "🐳 Building ${CI_REGISTRY_IMAGE}/${this_image}:${this_commit_tag} 🐳";
         docker pull $CI_REGISTRY_IMAGE/${this_image}:unstable || true;
         docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $CI_REGISTRY_IMAGE/${this_image}:unstable --tag $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag} ${DOCKER_COMMON_BUILD_ARGS} . ;
         echo "🐳 Pushing ${CI_REGISTRY_IMAGE}:${this_image}:${this_commit_tag} 🐳";
         docker push $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag};

LDAP Admin docker build:
  stage: build
  tags:
    - autoscale-large
  image: "${DOCKER_IMAGE}"
  services:
    - name:  "${DOCKER_DIND_IMAGE}"
      alias: docker
  variables:
    DOCKER_BUILDKIT:      1
    DOCKER_TLS_CERTDIR:   ""
    DOCKER_HOST:          "tcp://docker:2375"
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - >
         this_image="monocle-ldap-admin";
         cd "${CI_PROJECT_DIR}/ldap-admin";
         this_commit_tag="commit-${CI_COMMIT_SHORT_SHA}";
         echo "🐳 Building ${CI_REGISTRY_IMAGE}/${this_image}:${this_commit_tag} 🐳";
         docker pull $CI_REGISTRY_IMAGE/${this_image}:unstable || true;
         docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $CI_REGISTRY_IMAGE/${this_image}:unstable --tag $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag}  ${DOCKER_COMMON_BUILD_ARGS} . ;
         echo "🐳 Pushing ${CI_REGISTRY_IMAGE}:${this_image}:${this_commit_tag} 🐳";
         docker push $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag};

Dashboard API unit tests:
  stage: test
  only:
    - branches
  tags:
    - openstack-autoscale-theta
  image: "${CI_REGISTRY_IMAGE}/monocle-${DASH_API_CONTEXT}:commit-${CI_COMMIT_SHORT_SHA}"
  before_script:
    - cd "${DASH_API_CONTEXT}"
  script:
    - ./unittests.sh
    - coverage report --show-missing --fail-under 85
    - coverage html
  coverage: /^TOTAL.+?(\d+\%)$/
  artifacts:
    when: always
    paths:
      - ${DASH_API_CONTEXT}/htmlcov


Data view unit tests:
  stage: test
  only:
    - branches
  tags:
    - openstack-autoscale-theta
  image: "${CI_REGISTRY_IMAGE}/monocle-${DASH_API_CONTEXT}:commit-${CI_COMMIT_SHORT_SHA}"
  before_script:
    - cd "${DATA_VIEW_CONTEXT}"
  script:
    - ./unittests.sh
    - coverage report --fail-under 60
    - coverage html
  coverage: /^TOTAL.+?(\d+\%)$/
  artifacts:
    when: always
    paths:
      - ${DATA_VIEW_CONTEXT}/htmlcov


Metadata API for JUNO unit tests:
  stage: test
  only:
    - branches
  tags:
    - openstack-autoscale-theta
  image: "${CI_REGISTRY_IMAGE}/monocle-${METADATA_CONTEXT}-juno:commit-${CI_COMMIT_SHORT_SHA}"
  before_script:
    - cd "/app"
  script:
    - ./unittests.sh
    - coverage report --show-missing --fail-under 85
    - coverage html
  coverage: /^TOTAL.+?(\d+\%)$/
  artifacts:
    when: always
    paths:
      - ${METADATA_CONTEXT}/htmlcov

Metadata API for GPS unit tests:
  stage: test
  only:
    - branches
  tags:
    - openstack-autoscale-theta
  image: "${CI_REGISTRY_IMAGE}/monocle-${METADATA_CONTEXT}-gps:commit-${CI_COMMIT_SHORT_SHA}"
  before_script:
    - cd "/app"
  script:
    - ./unittests.sh
    - coverage report --show-missing --fail-under 85
    - coverage html
  coverage: /^TOTAL.+?(\d+\%)$/
  artifacts:
    when: always
    paths:
      - ${METADATA_CONTEXT}/htmlcov

Front end unit tests:
  stage: test
  only:
    - branches
  tags:
    - openstack-autoscale-theta
  image: "${CI_REGISTRY_IMAGE}/monocle-${FRONTEND_CONTEXT}:commit-${CI_COMMIT_SHORT_SHA}"
  before_script:
    - cd /app
  script:
    - npm run test:coverage # Coverage thresholds in package.json
    - npm run test:summary
  coverage: /^Branches\s*:\s*([^%]+)/
  artifacts:
    when: always
    paths:
      - /app/coverage/lcov-report


QC data unit tests:
  stage: test
  only:
    - branches
  tags:
    - openstack-autoscale-theta
  image: "${CI_REGISTRY_IMAGE}/monocle-${DASH_API_CONTEXT}:commit-${CI_COMMIT_SHORT_SHA}"
  before_script:
    - cd "${QC_DATA_CONTEXT}"
  script:
    - ./unittests.sh
    - coverage report --fail-under 60
    - coverage html
  coverage: /^TOTAL.+?(\d+\%)$/
  artifacts:
    when: always
    paths:
      - ${QC_DATA_CONTEXT}/htmlcov


# at every merge to master, tag the latest image builds as 'unstable'
# (runs for any commit to master, but these should all be merges)
Docker tags for merge:
  stage: docker_tags_for_merges_and_releases
  only:
    - master
  tags:
    - openstack-autoscale-theta
  image: "${DOCKER_IMAGE}"
  services:
    - name:  "${DOCKER_DIND_IMAGE}"
      alias: docker
  variables:
    # only docker, don't need to clone repo
    GIT_STRATEGY: none
    DOCKER_BUILDKIT:      1
    DOCKER_TLS_CERTDIR:   ""
    DOCKER_HOST:          "tcp://docker:2375"
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - >
         for this_image in $DOCKER_IMAGE_LIST;
         do
            this_commit_tag="commit-${CI_COMMIT_SHORT_SHA}";
            docker pull $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag};
            docker tag  $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag} $CI_REGISTRY_IMAGE/${this_image}:unstable;
            echo "🐳 Pushing ${CI_REGISTRY_IMAGE}:${this_image}:unstable 🐳";
            docker push $CI_REGISTRY_IMAGE/${this_image}:unstable;
         done


# at every release/tag, tag the images built from the latest image builds with the release tag and also as 'latest'
Docker tags for release:
  stage: docker_tags_for_merges_and_releases
  only:
    - tags
  tags:
    - openstack-autoscale-theta
  image: "${DOCKER_IMAGE}"
  services:
    - name:  "${DOCKER_DIND_IMAGE}"
      alias: docker
  variables:
    # only docker, don't need to clone repo
    GIT_STRATEGY: none
    DOCKER_BUILDKIT: 1
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - >
         for this_image in $DOCKER_IMAGE_LIST;
         do
            this_commit_tag="commit-${CI_COMMIT_SHORT_SHA}";
            docker pull $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag};
            for this_tag in $CI_COMMIT_REF_NAME 'latest';
            do
               docker tag  $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag} $CI_REGISTRY_IMAGE/${this_image}:${this_tag};
               echo "🐳 Pushing ${CI_REGISTRY_IMAGE}:${this_image}:${this_tag} 🐳";
               docker push $CI_REGISTRY_IMAGE/${this_image}:${this_tag};
            done;
         done
