
stages:
  - unit_test
  - integration_test
  
  
variables:
  CODECOV_TOKEN: "97dd07b5-c730-490a-a30f-b7d3ca3e023c"
  DOCKER_INTEGRATION_TEST_IMAGE: "${CI_REGISTRY_IMAGE}/gitlab-ci-node-with-docker:latest"
  DOCKER_DIND_IMAGE: "${CI_REGISTRY_IMAGE}/gitlab-ci-dind:latest"
  
  
API unit tests:
  stage: unit_test
  tags:
    - openstack-autoscale-theta
  variables:
    DJANGO_SETTINGS_MODULE: "juno.settings.unittest"
  image: "python:3.7"
  before_script:
    - cd api
    - pip install pipenv
    - pipenv install --system
    - pip install codecov
  script:
    - coverage run ./manage.py test && codecov --commit "${CI_COMMIT_SHA}" --token "${CODECOV_TOKEN}" --required
   
    
App unit tests:
  stage: unit_test
  tags:
    - openstack-autoscale-theta
  image: "node:12"
  before_script:
    - apt-get -qq update
    - apt-get install -y python-pip
    - pip install codecov
    - cd ui
    - yarn install
    
  script:
    - yarn test:ci && codecov --commit "${CI_COMMIT_SHA}" --token "${CODECOV_TOKEN}" --required

    
Integration tests:
  stage: integration_test
  tags:
    - openstack-autoscale-theta
  image: "${DOCKER_INTEGRATION_TEST_IMAGE}"
  services:
    - name:  "${DOCKER_DIND_IMAGE}"
      alias: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  before_script:
    - echo -n "${CI_JOB_TOKEN}" | docker login -u gitlab-ci-token --password-stdin "${CI_REGISTRY}"
    - cd "${CI_PROJECT_DIR}/e2e"; pwd
    - yarn install --verbose
    - cd "${CI_PROJECT_DIR}"; pwd
    - docker-compose -f docker-compose.e2e.yml build
    - docker-compose -f docker-compose.e2e.yml up -d
  script:
    - cd "${CI_PROJECT_DIR}/e2e"; pwd
    - yarn test:ci
