# codecov removed 2021-04-15 after security breach notice

stages:
  - build
  - test
  - docker_tags_for_merges_and_releases


variables:
  DASH_CONTEXT:             "dash"
  DASH_API_CONTEXT:         "dash-api"
  METADATA_CONTEXT:         "metadata"
  FRONTEND_CONTEXT:         "frontend"
  DOCKER_BUILD_LIST:        "${DASH_API_CONTEXT}/juno ${DASH_CONTEXT} ${METADATA_CONTEXT}/juno ${FRONTEND_CONTEXT} proxy ldap-admin"
  DOCKER_IMAGE:             "${CI_REGISTRY_IMAGE}/docker:19"
  DOCKER_DIND_IMAGE:        "${CI_REGISTRY_IMAGE}/gitlab-ci-dind:latest"

# at every git push, build docker images in subdirectories in DOCKER_BUILD_LIST
# push the images to the container registry  with the commit SHA-1 as the tag
Docker builds:
  stage: build
  tags:
    - openstack-autoscale-theta
  image: "${DOCKER_IMAGE}"
  services:
    - name:  "${DOCKER_DIND_IMAGE}"
      alias: docker
  variables:
    DOCKER_BUILDKIT:      1
    DOCKER_TLS_CERTDIR:   ""
    DOCKER_HOST:          "tcp://docker:2375"
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - >
         for this_context in $DOCKER_BUILD_LIST;
         do
            cd "${CI_PROJECT_DIR}/${this_context}";
            if [[ "metadata/juno" == ${this_context} ]]; then
               this_image="monocle-${METADATA_CONTEXT}"
            elif [[ "dash-api/juno" == ${this_context} ]]; then
               this_image="monocle-${DASH_API_CONTEXT}"
            else
               this_image="monocle-${this_context}"
            fi;
            this_commit_tag="commit-${CI_COMMIT_SHORT_SHA}";
            echo "🐳 Building ${CI_REGISTRY_IMAGE}/${this_image}:${this_commit_tag} 🐳";
            docker pull $CI_REGISTRY_IMAGE/${this_image}:unstable || true;
            docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $CI_REGISTRY_IMAGE/${this_image}:unstable --tag $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag} . ;
            echo "🐳 Pushing ${CI_REGISTRY_IMAGE}:${this_image}:${this_commit_tag} 🐳";
            docker push $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag};
         done


Dashboard unit tests:
  stage: test
  only:
    - branches
  tags:
    - openstack-autoscale-theta
  image: "${CI_REGISTRY_IMAGE}/monocle-${DASH_CONTEXT}:commit-${CI_COMMIT_SHORT_SHA}"
  before_script:
    # codecov temporarily disabled 2021-04-15 after security breach notice
    # - pip install codecov
    - cd "${DASH_CONTEXT}"
  script:
    - ./unittests.sh
    - coverage report --fail-under 90
    - coverage html
  coverage: /^TOTAL.+?(\d+\%)$/
  artifacts:
    when: always
    paths:
      - ${DASH_CONTEXT}/htmlcov
  # codecov temporarily disabled 2021-04-15 after security breach notice
  # after_script:
    # - codecov --commit "${CI_COMMIT_SHA}" --token "${CODECOV_TOKEN}" --required


Dashboard API unit tests:
  stage: test
  only:
    - branches
  tags:
    - openstack-autoscale-theta
  image: "${CI_REGISTRY_IMAGE}/monocle-${DASH_API_CONTEXT}:commit-${CI_COMMIT_SHORT_SHA}"
  before_script:
    # codecov temporarily disabled 2021-04-15 after security breach notice
    # - pip install codecov
    - cd "${DASH_API_CONTEXT}/juno"
  script:
    - ./unittests.sh
    - coverage report --fail-under 90
    - coverage html
  coverage: /^TOTAL.+?(\d+\%)$/
  artifacts:
    when: always
    paths:
      - ${DASH_API_CONTEXT}/juno/htmlcov
  # codecov temporarily disabled 2021-04-15 after security breach notice
  # after_script:
    # - codecov --commit "${CI_COMMIT_SHA}" --token "${CODECOV_TOKEN}" --required


Data view unit tests:
  stage: test
  only:
    - branches
  tags:
    - openstack-autoscale-theta
  image: "${CI_REGISTRY_IMAGE}/monocle-${DASH_CONTEXT}:commit-${CI_COMMIT_SHORT_SHA}"
  before_script:
    - cd data_view
  script:
    - ./unittests.sh
    - coverage report --fail-under 25
    - coverage html
  coverage: /^TOTAL.+?(\d+\%)$/
  artifacts:
    when: always
    paths:
      - data_view/htmlcov


Metadata unit tests:
  stage: test
  only:
    - branches
  tags:
    - openstack-autoscale-theta
  image: "${CI_REGISTRY_IMAGE}/monocle-${METADATA_CONTEXT}:commit-${CI_COMMIT_SHORT_SHA}"
  before_script:
    # codecov temporarily disabled 2021-04-15 after security breach notice
    # - pip install codecov
    - cd "${METADATA_CONTEXT}/juno"
  script:
    - ./unittests.sh
    - coverage report --fail-under 90
    - coverage html
  coverage: /^TOTAL.+?(\d+\%)$/
  artifacts:
    when: always
    paths:
      - ${METADATA_CONTEXT}/juno/htmlcov
  # codecov temporarily disabled 2021-04-15 after security breach notice
  # after_script:
    # - codecov --commit "${CI_COMMIT_SHA}" --token "${CODECOV_TOKEN}" --required


Front end unit tests:
  stage: test
  only:
    - branches
  tags:
    - openstack-autoscale-theta
  image: "${CI_REGISTRY_IMAGE}/monocle-${FRONTEND_CONTEXT}:commit-${CI_COMMIT_SHORT_SHA}"
  before_script:
    - cd /app
  script:
    - npm run test:coverage # Coverage thresholds in package.json
  artifacts:
    when: always
    paths:
      - /app/coverage/lcov-report


# at every merge to master, tag the latest image builds as 'unstable'
# (runs for any commit to master, but these should all be merges)
Docker tags for merge:
  variables:
    # only docker, don't need to clone repo
    GIT_STRATEGY: none
  stage: docker_tags_for_merges_and_releases
  only:
    - master
  tags:
    - openstack-autoscale-theta
  image: "${DOCKER_IMAGE}"
  services:
    - name:  "${DOCKER_DIND_IMAGE}"
      alias: docker
  variables:
    DOCKER_BUILDKIT:      1
    DOCKER_TLS_CERTDIR:   ""
    DOCKER_HOST:          "tcp://docker:2375"
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - >
         for this_context in $DOCKER_BUILD_LIST;
         do
            if [[ "metadata/juno" == ${this_context} ]]; then
               this_image="monocle-${METADATA_CONTEXT}"
            elif [[ "dash-api/juno" == ${this_context} ]]; then
               this_image="monocle-${DASH_API_CONTEXT}"
            else
               this_image="monocle-${this_context}"
            fi;
            this_commit_tag="commit-${CI_COMMIT_SHORT_SHA}";
            docker pull $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag};
            docker tag  $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag} $CI_REGISTRY_IMAGE/${this_image}:unstable;
            echo "🐳 Pushing ${CI_REGISTRY_IMAGE}:${this_image}:unstable 🐳";
            docker push $CI_REGISTRY_IMAGE/${this_image}:unstable;
         done


# at every release/tag, tag the images built from the latest image builds with the release tag and also as 'latest'
Docker tags for release:
  variables:
    # only docker, don't need to clone repo
    GIT_STRATEGY: none
  stage: docker_tags_for_merges_and_releases
  only:
    - tags
  tags:
    - openstack-autoscale-theta
  image: "${DOCKER_IMAGE}"
  services:
    - name:  "${DOCKER_DIND_IMAGE}"
      alias: docker
  variables:
    DOCKER_BUILDKIT:      1
    DOCKER_TLS_CERTDIR:   ""
    DOCKER_HOST:          "tcp://docker:2375"
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - >
         for this_context in $DOCKER_BUILD_LIST;
         do
            if [[ "metadata/juno" == ${this_context} ]]; then
               this_image="monocle-${METADATA_CONTEXT}"
            elif [[ "dash-api/juno" == ${this_context} ]]; then
               this_image="monocle-${DASH_API_CONTEXT}"
            else
               this_image="monocle-${this_context}"
            fi;
            this_commit_tag="commit-${CI_COMMIT_SHORT_SHA}";
            docker pull $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag};
            for this_tag in $CI_COMMIT_REF_NAME 'latest';
            do
               docker tag  $CI_REGISTRY_IMAGE/${this_image}:${this_commit_tag} $CI_REGISTRY_IMAGE/${this_image}:${this_tag};
               echo "🐳 Pushing ${CI_REGISTRY_IMAGE}:${this_image}:${this_tag} 🐳";
               docker push $CI_REGISTRY_IMAGE/${this_image}:${this_tag};
            done;
         done
