default_language_version:
  # Keep this version in sync w/ the one from the code formatting check stage in `./.gitlab-ci.yml`.
  python: python3.8
# IMPORTANT: if you update a version of a package, update the version of the corresponding package in `requirements-ci.py`, or `./.gitlab-ci.yml` if it's an NPM package, as well.
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Black (Python)
        args:
          - --line-length=120
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (Python)
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: flake8 (Python)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        name: Prettier (FE)
        # Keep these args in sync w/ Prettier args in `./.gitlab-ci.yml` (besides `--write` arg, as the CI only checks, w/o writing):
        args: ["--no-config", "--ignore-path", ".eslintignore", "--write"]
        additional_dependencies:
          - prettier@2.6.2
          - prettier-plugin-svelte@2.7.0
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.16.0
    hooks:
      - id: eslint
        name: ESLint (FE)
        # If you add or update the args besides `--fix`, do the same for ESLint args in `./.gitlab-ci.yml`:
        args:
          - --fix
        files: \.svelte|js$
        types: [file]
        additional_dependencies:
          - eslint@8.16.0
          - eslint-plugin-jest@26.4.6
          - eslint-plugin-svelte3@4.0.0
          - eslint-config-prettier@8.5.0
