# Fail on the first failure.
fail_fast: true
default_language_version:
  # Keep this version in sync w/ the one from the code formatting check stage in `./.gitlab-ci.yml`.
  python: python3.8
# Important: if you update a version of a package, update the version of the corresponding package in `requirements-ci.py` as well.
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Black (Python)
        args:
          - --line-length=120
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (Python)
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: flake8 (Python)
