language: python
python:
  - "3.7"
before_install:
  - cd api
install:
  - pip install pipenv
  - pipenv install
  - pipenv install codecov
script:
  - coverage run ./manage.py test
after_success:
  - codecov