version: '3'
services:
  ui:
    image: "sangerpathogens/monocle-app:<VERSION>"
    ports:
        - "80:80"
    volumes:
        - ./settings.js:/usr/share/nginx/html/settings.js
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - api
  api:
    image: "sangerpathogens/monocle-api:<VERSION>"
    ports:
        - "8000:80"
    volumes:
        - data:/data
        - ./my.cnf:/etc/mysql/my.cnf
    environment:
        - HOSTNAME=<HOSTNAME>
        - SECRET_KEY=<SECRET_KEY>
        - DJANGO_SETTINGS_MODULE=juno.settings.prod

# Volume needs driver, since it's a mounted S3 bucket
volumes:
    data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/pathpipe/monocle_juno_test

# Change address range of default compose network so as
# not to clash with ISG infrastructure
networks:
    default:
       ipam:
          config:
              - subnet: 192.168.192.0/18
