version: '3'
services:
  proxy:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/monocle-proxy:<DOCKERTAG>"
    ports:
        - "80:80"
    restart: unless-stopped
    security_opt:
       - no-new-privileges
    cap_drop:
       - ALL
    cap_add:
       - NET_BIND_SERVICE
    tmpfs:
       - "/run:rw,noexec,nosuid"
       - "/tmp:rw,noexec,nosuid"
    volumes:
        - ./nginx.proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - api
  ui:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/monocle-ui:<DOCKERTAG>"
    expose:
        - "80"
    restart: unless-stopped
    security_opt:
       - no-new-privileges
    cap_drop:
       - ALL
    cap_add:
       - NET_BIND_SERVICE
       - FOWNER
       - CHOWN
       - SETGID
       - SETUID
    tmpfs:
       - "/run:rw,noexec,nosuid"
       - "/tmp:rw,noexec,nosuid"
    volumes:
        - ./settings.js:/usr/share/nginx/html/settings.js
        - ./nginx.ui.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - api
  api:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/monocle-api:<DOCKERTAG>"
    expose:
        - "80"
    restart: unless-stopped
    security_opt:
       - no-new-privileges
    cap_drop:
       - ALL
    cap_add:
       - NET_BIND_SERVICE
       - DAC_OVERRIDE
       - SETGID
       - SETUID
    tmpfs:
       - "/run:rw,noexec,nosuid"
       - "/tmp:rw,noexec,nosuid"
    volumes:
        - data:/data
        - ./my.cnf:/etc/mysql/my.cnf
    environment:
        - HOSTNAME=<HOSTNAME>
        - HOSTNAME_PUBLIC=<HOSTNAME_PUBLIC>
        - SECRET_KEY=<SECRET_KEY>
        - DJANGO_SETTINGS_MODULE=juno.settings.prod
  metadata-api:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/monocle-metadata:<DOCKERTAG>"
    expose:
      - "80"
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - "/run:rw,noexec,nosuid"
      - "/tmp:rw,noexec,nosuid"
    volumes:
      - ./metadata-api.json:/app/config.json
      - ./my.cnf:/app/my.cnf
    environment:
      - ENABLE_SWAGGER_UI=false
      - API_TEST_MODE=false
  dash:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/monocle-dash:<DOCKERTAG>"
    expose:
        - "80"
    restart: unless-stopped
    security_opt:
       - no-new-privileges
    cap_drop:
       - ALL
    volumes:
        - data:/dash/data
        - ./my.cnf:/dash/my.cnf

# Volume needs driver, since it's a mounted S3 bucket
volumes:
    data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/<USER>/monocle_juno

# Change address range of default compose network so as
# not to clash with ISG infrastructure
networks:
    default:
       ipam:
          config:
              - subnet: 192.168.192.0/18
