version: '3'
services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    command: yarn start
    ports:
        - "3000:3000"
    volumes:
        - ./ui:/app
    stdin_open: true
    depends_on:
        - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    ports:
        - "8000:8000"
    volumes:
        - ./api:/app
        - ./mock-data:/data
