version: '3'
services:
  ui:
    image: "sangerpathogens/monocle-app:VERSION"
    ports:
        - "80:80"
    volumes:
        - ./settings.js:/usr/share/nginx/html/settings.js
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - api
  api:
    image: "sangerpathogens/monocle-api:VERSION"
    ports:
        - "8000:80"
    volumes:
        - ./mock-data/:/mock-data/
