version: "3"
services:
  ui:
    build:
      context: ./ui
    ports:
      - "3001:80"
    volumes:
      - ./ui/settings.e2e.js:/usr/share/nginx/html/settings.js
      - ./ui/nginx.e2e.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  api:
    build:
      context: ./api
    entrypoint: /app/entrypoint.e2e.sh
    ports:
      - "8001:80"
    volumes:
      - ./mock-data:/data
    environment:
      DJANGO_SETTINGS_MODULE: juno.settings.e2e
    depends_on:
      - db
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "9001:3306"
  metadata-api:
    build:
      context: ./metadata-e2e-dummy
    ports:
      - "8002:80"
  dash:
    build:
      context: ./dash-e2e-dummy
    ports:
      - "8003:80"
