version: '3'
services:
    cypress:
        image: "cypress/included:4.6.0"
        user: root
        links:
            - ui
            - api
        privileged: true
        environment:
            - CYPRESS_BASE_URL=http://ui:80/
        working_dir: /e2e
        volumes:
            - ./e2e:/e2e
            - ./e2e/ssh/id_rsa:/root/.ssh/id_rsa
            - ./e2e/ssh/config:/root/.ssh/config
        depends_on:
            - ui
    ui:
        build:
            context: ./ui
        ports:
            - "3001:80"
        volumes:
            - ./ui/settings.test.js:/usr/share/nginx/html/settings.js
            - ./ui/nginx.prod.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - api
    api:
        build:
            context: ./api
            dockerfile: Dockerfile.e2e
        ports:
            - "8001:80"
            - "2222:22"
        volumes:
            - ./e2e/ssh/id_rsa.pub:/root/.ssh/authorized_keys
        # tty: true
        # stdin_open: true
