version: '3'
services:
  proxy:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/monocle-proxy:<DOCKERTAG>"
    ports:
        - "80:80"
    restart: unless-stopped
    security_opt:
       - no-new-privileges
    cap_drop:
       - ALL
    cap_add:
       - FOWNER
       - CHOWN
       - SETGID
       - SETUID
    tmpfs:
       - "/run:rw,noexec,nosuid"
       - "/tmp:rw,noexec,nosuid"
    volumes:
       - ./nginx.proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
       - ui
       - api
       - dash
       - metadata-api
       - ldap-admin
  ui:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/monocle-ui:<DOCKERTAG>"
    expose:
        - "80"
    restart: unless-stopped
    security_opt:
       - no-new-privileges
    cap_drop:
       - ALL
    cap_add:
       - NET_BIND_SERVICE
       - FOWNER
       - CHOWN
       - SETGID
       - SETUID
    tmpfs:
       - "/run:rw,noexec,nosuid"
       - "/tmp:rw,noexec,nosuid"
    volumes:
        - ./settings.js:/usr/share/nginx/html/settings.js
        - ./nginx.ui.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - api
  api:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/monocle-api:<DOCKERTAG>"
    expose:
        - "80"
    restart: unless-stopped
    security_opt:
       - no-new-privileges
    cap_drop:
       - ALL
    cap_add:
       - NET_BIND_SERVICE
       - DAC_OVERRIDE
       - SETGID
       - SETUID
    tmpfs:
       - "/run:rw,noexec,nosuid"
       - "/tmp:rw,noexec,nosuid"
    volumes:
        - data:/data
        - ./my.cnf:/etc/mysql/my.cnf
    environment:
        - HOSTNAME=<HOSTNAME>
        - HOSTNAME_PUBLIC=<HOSTNAME_PUBLIC>
        - SECRET_KEY=<SECRET_KEY>
        - DJANGO_SETTINGS_MODULE=juno.settings.prod
  metadata-api:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/monocle-metadata:<DOCKERTAG>"
    expose:
      - "80"
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - "/run:rw,noexec,nosuid"
      - "/tmp:rw,noexec,nosuid"
    volumes:
      - ./metadata-api.json:/app/config.json
      - ./my.cnf:/app/my.cnf
    environment:
      - ENABLE_SWAGGER_UI=false
      - API_TEST_MODE=false
  dash:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/monocle-dash:<DOCKERTAG>"
    expose:
       - "80"
    restart: unless-stopped
    security_opt:
       - no-new-privileges
    cap_drop:
       - ALL
    tmpfs:
       - "/run:rw,noexec,nosuid"
       - "/tmp:rw,noexec,nosuid"
    volumes:
       - data:/dash/data
       - ./my.cnf:/dash/my.cnf
  monocle-ldap:
    # temporarily use default image; should create out own (https://github.com/osixia/docker-openldap#advanced-user-guide)
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/osixia/openldap:1.5.0"
    expose:
        - "80"
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - CHOWN
      - FOWNER
      - KILL
      - SETGID
      - SETUID
    tmpfs:
      - "/run:rw,noexec,nosuid"
      - "/tmp:rw,noexec,nosuid"
    volumes:
      - ./openldap-env.yaml:/container/environment/01-custom/my-env.yaml
      - ./openldap-data/var/lib/ldap:/var/lib/ldap
      - ./openldap-data/etc/ldap/slapd.d:/etc/ldap/slapd.d
      # this next directory isn't mentioned in the documentation, but the container won't start without it
      - ./openldap-data/var/run/slapd:/var/run/slapd
  ldap-admin:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/osixia/phpldapadmin:0.9.0"
    expose:
      - "80"
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - CHOWN
      - FOWNER
      - SETGID
      - SETUID
    tmpfs:
      - "/tmp:rw,noexec,nosuid"
    volumes:
      # this next directory isn't mentioned in the documentation, but the container won't start without it
      - ./phpldapadmin-data/var/lock:/var/lock
    environment:
      - PHPLDAPADMIN_HTTPS=false
      # make sure the host name matches the name of the openldap service (above)
      - PHPLDAPADMIN_LDAP_HOSTS=monocle-ldap
   

# Volume needs driver, since it's a mounted S3 bucket
volumes:
    data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/<USER>/monocle_juno

# Change address range of default compose network so as
# not to clash with ISG infrastructure
networks:
    default:
       ipam:
          config:
              - subnet: 192.168.192.0/18
