version: '3'
services:
  ui:
    image: "sangerpathogens/monocle-app:<VERSION>"
    ports:
        - "80:80"
        - "8000:80"
    restart: unless-stopped
    security_opt:
       - no-new-privileges
    cap_drop:
       - ALL
    cap_add:
       - NET_BIND_SERVICE
       - FOWNER
       - CHOWN
       - SETGID
       - SETUID
    tmpfs:
       - "/run:rw,noexec,nosuid"
       - "/tmp:rw,noexec,nosuid"
    volumes:
        - ./settings.js:/usr/share/nginx/html/settings.js
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - api
  api:
    image: "sangerpathogens/monocle-api:<VERSION>"
    expose:
        - "80"
    restart: unless-stopped
    security_opt:
       - no-new-privileges
    cap_drop:
       - ALL
    cap_add:
       - NET_BIND_SERVICE
       - DAC_OVERRIDE
       - SETGID
       - SETUID
    tmpfs:
       - "/run:rw,noexec,nosuid"
       - "/tmp:rw,noexec,nosuid"
    volumes:
        - data:/data
        - ./my.cnf:/etc/mysql/my.cnf
    environment:
        - HOSTNAME=<HOSTNAME>
        - SECRET_KEY=<SECRET_KEY>
        - DJANGO_SETTINGS_MODULE=juno.settings.prod

# Volume needs driver, since it's a mounted S3 bucket
volumes:
    data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/<USER>/monocle_juno

# Change address range of default compose network so as
# not to clash with ISG infrastructure
networks:
    default:
       ipam:
          config:
              - subnet: 192.168.192.0/18
