version: '3'
services:
  proxy:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/monocle-proxy:<DOCKERTAG>"
    ports:
        - "80:80"
        - "8000:8000"
    restart: unless-stopped
    security_opt:
       - no-new-privileges
    cap_drop:
       - ALL
    cap_add:
       - NET_BIND_SERVICE
       - FOWNER
       - CHOWN
       - SETGID
       - SETUID
    tmpfs:
       - "/run:rw,noexec,nosuid"
       - "/tmp:rw,noexec,nosuid"
    volumes:
       - ./nginx.proxy.conf:/etc/nginx/conf.d/default.conf
       # data must have the same path in the container as on the host, otherwise symlinks from data_institution_view break
       - data:/home/<USER>/monocle_juno
       # data_institution_view must have the same path in the container as on the host, otherwise symlinks from data_downloads break
       - data_institution_view:/home/<USER>/monocle_juno_institution_view
       # the download directory must have mode 331, so users can access files via their own download path, but cannot see other download paths
       - data_downloads:/usr/share/nginx/html/downloads
    depends_on:
       - dash
       - metadata-api
       - monocle-ldap
       - ldap-admin
       - ldap-auth-daemon
  metadata-api:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/monocle-metadata:<DOCKERTAG>"
    expose:
      - "80"
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    tmpfs:
      - "/run:rw,noexec,nosuid"
      - "/tmp:rw,noexec,nosuid"
    volumes:
      - ./metadata-api.json:/app/config.json
      - ./my.cnf:/app/my.cnf
    environment:
      - ENABLE_SWAGGER_UI=false
      - API_TEST_MODE=false
  dash-api:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/monocle-dash-api:<DOCKERTAG>"
    expose:
      - "80"
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    tmpfs:
      - "/run:rw,noexec,nosuid"
      - "/tmp:rw,noexec,nosuid"
    environment:
      - ENABLE_SWAGGER_UI=false
      - API_TEST_MODE=false
  dash:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/monocle-dash:<DOCKERTAG>"
    user: <USER_UID>:<USER_GID>
    expose:
       - "80"
    restart: unless-stopped
    security_opt:
       - no-new-privileges
    cap_drop:
       - ALL
    cap_add:
       - NET_BIND_SERVICE
    tmpfs:
       - "/run:rw,noexec,nosuid"
       - "/tmp:rw,noexec,nosuid"
    volumes:
       - data:/dash/monocle_juno
       # data_institution_view must have the same path in the container as on the host, otherwise symlinks from data_downloads break
       - data_institution_view:/home/<USER>/monocle_juno_institution_view
       - data_downloads:/dash/monocle_juno_web_root/downloads
       - ./my.cnf:/dash/my.cnf
       - ./mlwh-api.yml:/dash/mlwh-api.yml
       - ./openldap-env.yaml:/dash/openldap-env.yaml
    environment:
       # this MUST be the same path as the mount point for data_institution_view
       - DATA_INSTITUTION_VIEW=/home/<USER>/monocle_juno_institution_view
       
  frontend:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/monocle-frontend:<DOCKERTAG>"
    expose:
       - "3000"
    restart: unless-stopped
    security_opt:
       - no-new-privileges
    cap_drop:
       - ALL
    cap_add:
       - NET_BIND_SERVICE
       - CHOWN
       - SETGID
       - SETUID
    depends_on:
      - dash-api
  monocle-ldap:
    # temporarily use default image; should create out own (https://github.com/osixia/docker-openldap#advanced-user-guide)
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/osixia/openldap:1.5.0"
    expose:
      - "389"
      - "636"
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
      - CHOWN
      - FOWNER
      - KILL
      - SETGID
      - SETUID
    tmpfs:
      - "/run:rw,noexec,nosuid"
      - "/tmp:rw,noexec,nosuid"
    volumes:
      - ./openldap-env.yaml:/container/environment/01-custom/my-env.yaml
      - ./openldap-data/var/lib/ldap:/var/lib/ldap
      - ./openldap-data/etc/ldap/slapd.d:/etc/ldap/slapd.d
      # this next directory isn't mentioned in the documentation, but the container won't start without it
      - ./openldap-data/var/run/slapd:/var/run/slapd
  ldap-admin:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/monocle-ldap-admin:<DOCKERTAG>"
    expose:
      - "80"
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
      - CHOWN
      - FOWNER
      - SETGID
      - SETUID
    tmpfs:
      - "/tmp:rw,noexec,nosuid"
    volumes:
      # this next directory isn't mentioned in the documentation, but the container won't start without it
      - ./phpldapadmin-data/var/lock:/var/lock
    depends_on:
      - monocle-ldap
    environment:
      - PHPLDAPADMIN_HTTPS=false
      # make sure the host name matches the name of the openldap service (above)
      - PHPLDAPADMIN_LDAP_HOSTS=monocle-ldap
  ldap-auth-daemon:
    image: "gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/monocle/bitnami/nginx-ldap-auth-daemon:0.20200116.0-debian-10-r329"
    expose:
      - "8888"
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - "/run:rw,noexec,nosuid"
      - "/tmp:rw,noexec,nosuid"
    depends_on:
      - monocle-ldap

# Volume needs driver, since it's a mounted S3 bucket
volumes:
    data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/<USER>/monocle_juno
    data_institution_view:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/<USER>/monocle_juno_institution_view
    data_downloads:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/<USER>/monocle_juno_web_root/downloads

# Change address range of default compose network so as
# not to clash with ISG infrastructure
networks:
    default:
       ipam:
          config:
              - subnet: 192.168.192.0/18
