openapi: '3.0.0'
info:
  title: "Monocle Sample Metadata API"
  version: "0.0.1"
  description: "A REST API for accessing/updating sample metadata"
  contact:
    email: "path-help@sanger.ac.uk"

servers:
  - url: /metadata
    description: Context path

paths:
  /metadata-upload:
    post:
      operationId: metadata.api.routes.update_sample_metadata
      summary: "Upload a new tab-delimited file of metadata"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                spreadsheet:
                  type: string
                  format: binary
      responses:
        200:
          description: "The upload succeeded"
        400:
          description: "The file has not passed validation"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    $ref: "#/components/schemas/ValidationErrors"
  /in-silico-upload:
    post:
      operationId: metadata.api.routes.update_in_silico_data
      summary: "Upload a new tab-delimited file of in silico data"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                spreadsheet:
                  type: string
                  format: binary
      responses:
        200:
          description: "The upload succeeded"
        400:
          description: "The file has not passed validation"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    $ref: "#/components/schemas/ValidationErrors"
  /download:
    post:
      operationId: metadata.api.routes.get_download_metadata
      summary: "Download the metadata for the given download keys"
      requestBody:
        description: "A list of sampleId keys"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DownloadKeys"
              examples: "[\"5903STDY8059122\", \"5903STDY8059054\"]"
      responses:
        200:
          description: "The download result set"
          content:
            application/json:
              schema:
                type: object
                properties:
                  download:
                    type: array
                    items:
                      $ref: "#/components/schemas/Metadata"
        400:
          description: "Invalid arguments provided"
        404:
          description: "No data could be found for the given download key"

  /download_in_silico_data:
    post:
      operationId: metadata.api.routes.get_download_in_silico_data
      summary: "Download the in silico data for the given download keys"
      requestBody:
        description: "A list of laneId keys"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DownloadKeys"
              examples: "[\"24936_2#76\", \"24937_1#22\"]"
      responses:
        200:
          description: "The download result set"
          content:
            application/json:
              schema:
                type: object
                properties:
                  download:
                    type: array
                    items:
                      $ref: "#/components/schemas/InSilicoData"
        400:
          description: "Invalid arguments provided"
        404:
          description: "No data could be found for the given download key"

  /institutions:
    get:
      operationId: metadata.api.routes.get_institution_names
      summary: "Gather the names for all institutions"
      responses:
        200:
          description: "The institution result set"
          content:
            application/json:
              schema:
                type: object
                properties:
                  institutions:
                    type: array
                    items:
                      $ref: "#/components/schemas/Institutions"
        404:
          description: "Institutions could not be gathered from database"

  /samples:
    post:
      operationId: metadata.api.routes.get_samples
      summary: "Gather all sample records"
      responses:
        200:
          description: "The sample result set"
          content:
            application/json:
              schema:
                type: object
                properties:
                  samples:
                    type: array
                    items:
                      $ref: "#/components/schemas/Metadata"
        404:
          description: "No data could be found for the given institutions or filters"

  /filters:
    post:
      operationId: metadata.api.routes.get_filtered_samples
      summary: "Gather filtered sample records"
      requestBody:
        description: "A dictionary of filters with lists of values"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Filters"
      responses:
        200:
          description: "List of sample ids"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Samples"
        404:
          description: "No data could be found for the given filters"

components:
  schemas:

    ValidationErrors:
      type: array
      items:
        type: string
      minItems: 0
      readOnly: true

    DownloadKeys:
      type: array
      items:
        type: string
        minLength: 3
        maxLength: 270
        pattern: '^\S+$'
      minItems: 1

    DownloadField:
      type: object
      required:
        - "name"
        - "value"
        - "order"
      properties:
        order:
          type: integer
          description: "An ordering integer index for the field"
          readOnly: true
        name:
          type: string
          description: "The name of the metadata field"
          readOnly: true
        value:
          type: string
          description: "The value of the metadata field"
          readOnly: true

    Filters:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
        minItems: 1
      minItems: 0
      example:
        serotype: ["IA", "IV"]

    Institutions:
      type: array
      items:
        type: string
        minLength: 1
        #maxLength: 255
        #pattern: '^[a-zA-Z0-9]*$'
      minItems: 1

    Samples:
      type: array
      items:
        type: string
        minLength: 1
      minItems: 1

    Metadata:
      type: object
      required:
        - "sanger_sample_id"
        - "lane_id"
        - "submitting_institution"
        - "supplier_sample_name"
        - "public_name"
        - "host_status"
        - "study_name"
        - "study_ref"
        - "selection_random"
        - "country"
        - "county_state"
        - "city"
        - "collection_year"
        - "collection_month"
        - "collection_day"
        - "host_species"
        - "gender"
        - "age_group"
        - "age_years"
        - "age_months"
        - "age_weeks"
        - "age_days"
        - "disease_type"
        - "disease_onset"
        - "isolation_source"
        - "serotype"
        - "serotype_method"
        - "infection_during_pregnancy"
        - "maternal_infection_type"
        - "gestational_age_weeks"
        - "birth_weight_gram"
        - "apgar_score"
        - "ceftizoxime"
        - "ceftizoxime_method"
        - "cefoxitin"
        - "cefoxitin_method"
        - "cefotaxime"
        - "cefotaxime_method"
        - "cefazolin"
        - "cefazolin_method"
        - "ampicillin"
        - "ampicillin_method"
        - "penicillin"
        - "penicillin_method"
        - "erythromycin"
        - "erythromycin_method"
        - "clindamycin"
        - "clindamycin_method"
        - "tetracycline"
        - "tetracycline_method"
        - "levofloxacin"
        - "levofloxacin_method"
        - "ciprofloxacin"
        - "ciprofloxacin_method"
        - "daptomycin"
        - "daptomycin_method"
        - "vancomycin"
        - "vancomycin_method"
        - "linezolid"
        - "linezolid_method"
      properties:
        sanger_sample_id:
          $ref: "#/components/schemas/DownloadField"
        lane_id:
          $ref: "#/components/schemas/DownloadField"
        submitting_institution:
          $ref: "#/components/schemas/DownloadField"
        supplier_sample_name:
          $ref: "#/components/schemas/DownloadField"
        public_name:
          $ref: "#/components/schemas/DownloadField"
        host_status:
          $ref: "#/components/schemas/DownloadField"
        study_name:
          $ref: "#/components/schemas/DownloadField"
        study_ref:
          $ref: "#/components/schemas/DownloadField"
        selection_random:
          $ref: "#/components/schemas/DownloadField"
        country:
          $ref: "#/components/schemas/DownloadField"
        county_state:
          $ref: "#/components/schemas/DownloadField"
        city:
          $ref: "#/components/schemas/DownloadField"
        collection_year:
          $ref: "#/components/schemas/DownloadField"
        collection_month:
          $ref: "#/components/schemas/DownloadField"
        collection_day:
          $ref: "#/components/schemas/DownloadField"
        host_species:
          $ref: "#/components/schemas/DownloadField"
        gender:
          $ref: "#/components/schemas/DownloadField"
        age_group:
          $ref: "#/components/schemas/DownloadField"
        age_years:
          $ref: "#/components/schemas/DownloadField"
        age_months:
          $ref: "#/components/schemas/DownloadField"
        age_weeks:
          $ref: "#/components/schemas/DownloadField"
        age_days:
          $ref: "#/components/schemas/DownloadField"
        disease_type:
          $ref: "#/components/schemas/DownloadField"
        disease_onset:
          $ref: "#/components/schemas/DownloadField"
        isolation_source:
          $ref: "#/components/schemas/DownloadField"
        serotype:
          $ref: "#/components/schemas/DownloadField"
        serotype_method:
          $ref: "#/components/schemas/DownloadField"
        infection_during_pregnancy:
          $ref: "#/components/schemas/DownloadField"
        maternal_infection_type:
          $ref: "#/components/schemas/DownloadField"
        gestational_age_weeks:
          $ref: "#/components/schemas/DownloadField"
        birth_weight_gram:
          $ref: "#/components/schemas/DownloadField"
        apgar_score:
          $ref: "#/components/schemas/DownloadField"
        ceftizoxime:
          $ref: "#/components/schemas/DownloadField"
        ceftizoxime_method:
          $ref: "#/components/schemas/DownloadField"
        cefoxitin:
          $ref: "#/components/schemas/DownloadField"
        cefoxitin_method:
          $ref: "#/components/schemas/DownloadField"
        cefotaxime:
          $ref: "#/components/schemas/DownloadField"
        cefotaxime_method:
          $ref: "#/components/schemas/DownloadField"
        cefazolin:
          $ref: "#/components/schemas/DownloadField"
        cefazolin_method:
          $ref: "#/components/schemas/DownloadField"
        ampicillin:
          $ref: "#/components/schemas/DownloadField"
        ampicillin_method:
          $ref: "#/components/schemas/DownloadField"
        penicillin:
          $ref: "#/components/schemas/DownloadField"
        penicillin_method:
          $ref: "#/components/schemas/DownloadField"
        erythromycin:
          $ref: "#/components/schemas/DownloadField"
        erythromycin_method:
          $ref: "#/components/schemas/DownloadField"
        clindamycin:
          $ref: "#/components/schemas/DownloadField"
        clindamycin_method:
          $ref: "#/components/schemas/DownloadField"
        tetracycline:
          $ref: "#/components/schemas/DownloadField"
        tetracycline_method:
          $ref: "#/components/schemas/DownloadField"
        levofloxacin:
          $ref: "#/components/schemas/DownloadField"
        levofloxacin_method:
          $ref: "#/components/schemas/DownloadField"
        ciprofloxacin:
          $ref: "#/components/schemas/DownloadField"
        ciprofloxacin_method:
          $ref: "#/components/schemas/DownloadField"
        daptomycin:
          $ref: "#/components/schemas/DownloadField"
        daptomycin_method:
          $ref: "#/components/schemas/DownloadField"
        vancomycin:
          $ref: "#/components/schemas/DownloadField"
        vancomycin_method:
          $ref: "#/components/schemas/DownloadField"
        linezolid:
          $ref: "#/components/schemas/DownloadField"
        linezolid_method:
          $ref: "#/components/schemas/DownloadField"

    InSilicoData:
      type: object
      required:
       - "lane_id"
       - "cps_type"
       - "ST"
       - "adhP"
       - "pheS"
       - "atr"
       - "glnA"
       - "sdhA"
       - "glcK"
       - "tkt"
       - "twenty_three_S1"
       - "twenty_three_S3"
       - "AAC6APH2"
       - "AADECC"
       - "ANT6"
       - "APH3III"
       - "APH3OTHER"
       - "CATPC194"
       - "CATQ"
       - "ERMA"
       - "ERMB"
       - "ERMT"
       - "LNUB"
       - "LNUC"
       - "LSAC"
       - "MEFA"
       - "MPHC"
       - "MSRA"
       - "MSRD"
       - "FOSA"
       - "GYRA"
       - "PARC"
       - "RPOBGBS_1"
       - "RPOBGBS_2"
       - "RPOBGBS_3"
       - "RPOBGBS_4"
       - "SUL2"
       - "TETB"
       - "TETL"
       - "TETM"
       - "TETO"
       - "TETS"
       - "ALP1"
       - "ALP23"
       - "ALPHA"
       - "HVGA"
       - "PI1"
       - "PI2A1"
       - "PI2A2"
       - "PI2B"
       - "RIB"
       - "SRR1"
       - "SRR2"
       - "GYRA_variant"
       - "PARC_variant"
      properties:
        lane_id:
          $ref: "#/components/schemas/DownloadField"
        cps_type:
          $ref: "#/components/schemas/DownloadField"
        ST:
          $ref: "#/components/schemas/DownloadField"
        adhP:
          $ref: "#/components/schemas/DownloadField"
        pheS:
          $ref: "#/components/schemas/DownloadField"
        atr:
          $ref: "#/components/schemas/DownloadField"
        glnA:
          $ref: "#/components/schemas/DownloadField"
        sdhA:
          $ref: "#/components/schemas/DownloadField"
        glcK:
          $ref: "#/components/schemas/DownloadField"
        tkt:
          $ref: "#/components/schemas/DownloadField"
        twenty_three_S1:
          $ref: "#/components/schemas/DownloadField"
        twenty_three_S3:
          $ref: "#/components/schemas/DownloadField"
        AAC6APH2:
          $ref: "#/components/schemas/DownloadField"
        AADECC:
          $ref: "#/components/schemas/DownloadField"
        ANT6:
          $ref: "#/components/schemas/DownloadField"
        APH3III:
          $ref: "#/components/schemas/DownloadField"
        APH3OTHER:
          $ref: "#/components/schemas/DownloadField"
        CATPC194:
          $ref: "#/components/schemas/DownloadField"
        CATQ:
          $ref: "#/components/schemas/DownloadField"
        ERMA:
          $ref: "#/components/schemas/DownloadField"
        ERMB:
          $ref: "#/components/schemas/DownloadField"
        ERMT:
          $ref: "#/components/schemas/DownloadField"
        LNUB:
          $ref: "#/components/schemas/DownloadField"
        LNUC:
          $ref: "#/components/schemas/DownloadField"
        LSAC:
          $ref: "#/components/schemas/DownloadField"
        MEFA:
          $ref: "#/components/schemas/DownloadField"
        MPHC:
          $ref: "#/components/schemas/DownloadField"
        MSRA:
          $ref: "#/components/schemas/DownloadField"
        MSRD:
          $ref: "#/components/schemas/DownloadField"
        FOSA:
          $ref: "#/components/schemas/DownloadField"
        GYRA:
          $ref: "#/components/schemas/DownloadField"
        PARC:
          $ref: "#/components/schemas/DownloadField"
        RPOBGBS_1:
          $ref: "#/components/schemas/DownloadField"
        RPOBGBS_2:
          $ref: "#/components/schemas/DownloadField"
        RPOBGBS_3:
          $ref: "#/components/schemas/DownloadField"
        RPOBGBS_4:
          $ref: "#/components/schemas/DownloadField"
        SUL2:
          $ref: "#/components/schemas/DownloadField"
        TETB:
          $ref: "#/components/schemas/DownloadField"
        TETL:
          $ref: "#/components/schemas/DownloadField"
        TETM:
          $ref: "#/components/schemas/DownloadField"
        TETO:
          $ref: "#/components/schemas/DownloadField"
        TETS:
          $ref: "#/components/schemas/DownloadField"
        ALP1:
          $ref: "#/components/schemas/DownloadField"
        ALP23:
          $ref: "#/components/schemas/DownloadField"
        ALPHA:
          $ref: "#/components/schemas/DownloadField"
        HVGA:
          $ref: "#/components/schemas/DownloadField"
        PI1:
          $ref: "#/components/schemas/DownloadField"
        PI2A1:
          $ref: "#/components/schemas/DownloadField"
        PI2A2:
          $ref: "#/components/schemas/DownloadField"
        PI2B:
          $ref: "#/components/schemas/DownloadField"
        RIB:
          $ref: "#/components/schemas/DownloadField"
        SRR1:
          $ref: "#/components/schemas/DownloadField"
        SRR2:
          $ref: "#/components/schemas/DownloadField"
        GYRA_variant:
          $ref: "#/components/schemas/DownloadField"
        PARC_variant:
          $ref: "#/components/schemas/DownloadField"
