# Generated by Django 3.0.6 on 2020-05-15 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('latitude',models.FloatField()),
                ('longitude',models.FloatField()),
                ('country', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('lane_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('sample_id', models.CharField(max_length=256, unique=True)),
                ('public_name', models.CharField(max_length=256, unique=True)),
                ('submitting_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='api.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='affiliations',
            field=models.ManyToManyField(related_name='affiliated_members', through='api.Affiliation', to='api.Institution'),
        ),
    ]
