# Generated by Django 3.0.6 on 2020-05-27 13:38

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=256)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('lane_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('sample_id', models.CharField(max_length=256, unique=True)),
                ('public_name', models.CharField(max_length=256, unique=True)),
                ('host_status', models.CharField(choices=[('carriage', 'Carriage'), ('sepsis', 'Sepsis'), ('bacteraemia', 'Bacteraemia'), ('meningitis', 'Meningitis'), ('pneumonia', 'Pneumonia'), ('urinary tract infection', 'Urinary Tract Infection'), ('skin and soft-tissue infection', 'Infection And Soft Tissue Infection'), ('osteomyelitis', 'Osteomyelitis'), ('endocarditis', 'Endocarditis'), ('septic arthritis', 'Septic Arthritis'), ('chorioamnionitis', 'Chorioamnionitis'), ('peritonitis', 'Peritonitis'), ('empyema', 'Empyema'), ('surgical site infection', 'Surgical Site Infection'), ('urosepsis', 'Urosepsis'), ('endometritis', 'Endometritis'), ('mastitis', 'Mastitis'), ('disease other', 'Disease Other')], max_length=256)),
                ('serotype', models.CharField(choices=[('Ia', 'Ia'), ('Ib', 'Ib'), ('II', 'Ii'), ('III', 'Iii'), ('IV', 'Iv'), ('V', 'V'), ('VI', 'Vi'), ('VII', 'Vii'), ('VIII', 'Viii'), ('IX', 'Ix'), ('NT', 'Nt'), ('unknown', 'Unknown')], max_length=7)),
                ('submitting_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='api.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='affiliations',
            field=models.ManyToManyField(related_name='affiliated_members', through='api.Affiliation', to='api.Institution'),
        ),
    ]
