# Generated by Django 3.1 on 2020-10-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    # NOTE: the following migration ops have been manually edited to get the primary key removal to work
    # on both mysql and sqlite.
    operations = [
        migrations.AlterField(
            model_name='sample',
            name='host_status',
            field=models.CharField(choices=[('carriage', 'Carriage'), ('sepsis', 'Sepsis'), ('bacteraemia', 'Bacteraemia'), ('meningitis', 'Meningitis'), ('pneumonia', 'Pneumonia'), ('urinary tract infection', 'Urinary Tract Infection'), ('skin and soft-tissue infection', 'Skin And Soft Tissue Infection'), ('osteomyelitis', 'Osteomyelitis'), ('endocarditis', 'Endocarditis'), ('septic arthritis', 'Septic Arthritis'), ('chorioamnionitis', 'Chorioamnionitis'), ('peritonitis', 'Peritonitis'), ('empyema', 'Empyema'), ('surgical site infection', 'Surgical Site Infection'), ('urosepsis', 'Urosepsis'), ('endometritis', 'Endometritis'), ('mastitis', 'Mastitis'), ('disease other', 'Disease Other')], max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='lane_id',
            field=models.CharField(max_length=256, primary_key=False, serialize=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='lane_id',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
