# Generated by Django 3.1 on 2021-03-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sampleid_pk_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='host_status',
            field=models.CharField(choices=[('carriage', 'Carriage'), ('sepsis', 'Sepsis'), ('bacteraemia', 'Bacteraemia'), ('meningitis', 'Meningitis'), ('pneumonia', 'Pneumonia'), ('urinary tract infection', 'Urinary Tract Infection'), ('skin and soft-tissue infection', 'Skin And Soft Tissue Infection'), ('osteomyelitis', 'Osteomyelitis'), ('endocarditis', 'Endocarditis'), ('septic arthritis', 'Septic Arthritis'), ('chorioamnionitis', 'Chorioamnionitis'), ('peritonitis', 'Peritonitis'), ('empyema', 'Empyema'), ('surgical site infection', 'Surgical Site Infection'), ('urosepsis', 'Urosepsis'), ('endometritis', 'Endometritis'), ('mastitis', 'Mastitis'), ('disease other', 'Disease Other'), ('invasive', 'Invasive')], max_length=256),
        ),
        migrations.AlterField(
            model_name='sample',
            name='serotype',
            field=models.CharField(max_length=7),
        ),
    ]
