# Generated by Django 3.0.6 on 2020-05-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200522_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='host',
            new_name='host_status',
        ),
    ]
