# Generated by Django 3.0.6 on 2020-05-15 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('affiliations', models.ManyToManyField(related_name='affiliated_members', through='api.Affiliation', to='api.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('lane_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('sample_id', models.CharField(max_length=256, unique=True)),
                ('public_name', models.CharField(max_length=256, unique=True)),
                ('submitting_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='api.Institution')),
            ],
        ),
        migrations.AddField(
            model_name='affiliation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Institution'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
