# **************************************************************
# Create gps tables
# **************************************************************

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- gps_sample table (metadata)

DROP TABLE IF EXISTS `gps_sample`;

CREATE TABLE `gps_sample` (
  `sample_name` VARCHAR(256) NOT NULL,
  `sanger_sample_id` VARCHAR(256) NOT NULL,
  `public_name` VARCHAR(256) NOT NULL,
  `study_name` VARCHAR(600),
  `submitting_institution` VARCHAR(256) NOT NULL,
  `selection_random` VARCHAR(10) DEFAULT NULL,
  `country` VARCHAR(90),
  `region` VARCHAR(90),
  `city` VARCHAR(200),
  `facility_where_collected` VARCHAR(256) DEFAULT NULL,
  `month_collection` VARCHAR(10) DEFAULT NULL,
  `year_collection` INT(11) DEFAULT NULL,
  `gender` VARCHAR(10) DEFAULT NULL,
  `age_years` INT(11) DEFAULT NULL,
  `age_months` INT(11) DEFAULT NULL,
  `age_days` INT(11) DEFAULT NULL,
  `clinical_manifestation` VARCHAR(256),
  `source` VARCHAR(100),
  `HIV_status` VARCHAR(10),
  `underlying_conditions` VARCHAR(256),
  `phenotypic_serotype_method` VARCHAR(100),
  `phenotypic_serotype` VARCHAR(100),
  `sequence_type` VARCHAR(256),
  `penicillin` VARCHAR(30),
  `AST_method_penicillin` VARCHAR(60),
  `amoxicillin` VARCHAR(30),
  `AST_method_amoxicillin` VARCHAR(60),
  `cefotaxime` VARCHAR(30),
  `AST_method_cefotaxime` VARCHAR(60),
  `ceftriaxone` VARCHAR(30),
  `AST_method_ceftriaxone` VARCHAR(60),
  `cefuroxime` VARCHAR(30),
  `AST_method_cefuroxime` VARCHAR(60),
  `Meropenem` VARCHAR(30),
  `AST_method_meropenem` VARCHAR(60),
  `erythromycin` VARCHAR(30),
  `AST_method_erythromycin` VARCHAR(60),
  `clindamycin` VARCHAR(30),
  `AST_method_clindamycin` VARCHAR(60),
  `trim_sulfa` VARCHAR(30),
  `AST_method_trim_sulfa` VARCHAR(60),
  `vancomycin` VARCHAR(30),
  `AST_method_vancomycin` VARCHAR(60),
  `linezolid` VARCHAR(30),
  `AST_method_linezolid` VARCHAR(60),
  `ciprofloxacin` VARCHAR(30),
  `AST_method_ciprofloxacin` VARCHAR(60),
  `chloramphenicol` VARCHAR(30),
  `AST_method_chloramphenicol` VARCHAR(60),
  `tetracycline` VARCHAR(30),
  `AST_method_tetracycline` VARCHAR(60),
  `levofloxacin` VARCHAR(30),
  `AST_method_levofloxacin` VARCHAR(60),
  `synercid` VARCHAR(30),
  `AST_method_synercid` VARCHAR(60),
  `rifampin` VARCHAR(30),
  `AST_method_rifampin` VARCHAR(60),
  `aroe` VARCHAR(100),
  `gdh` VARCHAR(100),
  `gki` VARCHAR(100),
  `recp` VARCHAR(100),
  `spi` VARCHAR(100),
  `xpt` VARCHAR(100),
  `ddl` VARCHAR(100),
  `comments` VARCHAR(256),
  `vaccine_period` VARCHAR(200),
  `intro_year` SMALLINT(6) DEFAULT NULL,
  `PCV_type` VARCHAR(100),
  `resolution` SMALLINT(4),
  PRIMARY KEY (`public_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- gps_in_silico table

DROP TABLE IF EXISTS `gps_in_silico`;

CREATE TABLE IF NOT EXISTS `gps_in_silico` (
  `lane_id` VARCHAR(256) NOT NULL,
  `public_name` VARCHAR(256) NOT NULL,
  `sample` VARCHAR(256) NOT NULL,
  `ERR` VARCHAR(256),
  `ERS` VARCHAR(256),
  `no_of_genome` SMALLINT(6) DEFAULT NULL,
  `duplicate` VARCHAR(30),
  `Paper_1` VARCHAR(30),
  `In_Silico_St` VARCHAR(20) NOT NULL,
  `Aroe` VARCHAR(30),
  `Gdh` VARCHAR(30),
  `Gki` VARCHAR(30),
  `Recp` VARCHAR(30),
  `Spi` VARCHAR(30),
  `Xpt` VARCHAR(30),
  `Ddl` VARCHAR(30),
  `country` VARCHAR(256),
  `Manifest_type` VARCHAR(30),
  `children_under_5yrs` VARCHAR(30),
  `GPSC_PoPUNK2` VARCHAR(30),
  `GPSC_PoPUNK2__colour` VARCHAR(30),
  `In_Silico_serotype` VARCHAR(30),
  `In_Silico_serotype__colour` VARCHAR(30),
  `PBP1A` VARCHAR(30),
  `PBP2B` VARCHAR(30),
  `PBP2X` VARCHAR(30),
  `WGS_PEN` VARCHAR(30),
  `WGS_PEN_SIR_Meningitis` VARCHAR(30),
  `WGS_PEN_SIR_Nonmeningitis` VARCHAR(30),
  `WGS_AMO` VARCHAR(30),
  `WGS_AMO_SIR` VARCHAR(30),
  `WGS_MER` VARCHAR(30),
  `WGS_MER_SIR` VARCHAR(30),
  `WGS_TAX` VARCHAR(30),
  `WGS_TAX_SIR_Meningitis` VARCHAR(30),
  `WGS_TAX_SIR_Nonmeningitis` VARCHAR(30),
  `WGS_CFT` VARCHAR(30),
  `WGS_CFT_SIR_Meningitis` VARCHAR(30),
  `WGS_CFT_SIR_Nonmeningitis` VARCHAR(30),
  `WGS_CFX` VARCHAR(30),
  `WGS_CFX_SIR` VARCHAR(30),
  `WGS_ERY` VARCHAR(30),
  `WGS_ERY_SIR` VARCHAR(30),
  `WGS_CLI` VARCHAR(30),
  `WGS_CLI_SIR` VARCHAR(30),
  `WGS_SYN` VARCHAR(30),
  `WGS_SYN_SIR` VARCHAR(30),
  `WGS_LZO` VARCHAR(30),
  `WGS_LZO_SIR` VARCHAR(30),
  `WGS_ERY_CLI` VARCHAR(30),
  `WGS_COT` VARCHAR(30),
  `WGS_COT_SIR` VARCHAR(30),
  `WGS_TET` VARCHAR(30),
  `WGS_TET_SIR` VARCHAR(30),
  `WGS_DOX` VARCHAR(30),
  `WGS_DOX_SIR` VARCHAR(30),
  `WGS_LFX` VARCHAR(30),
  `WGS_LFX_SIR` VARCHAR(30),
  `WGS_CHL` VARCHAR(30),
  `WGS_CHL_SIR` VARCHAR(30),
  `WGS_RIF` VARCHAR(30),
  `WGS_RIF_SIR` VARCHAR(30),
  `WGS_VAN` VARCHAR(30),
  `WGS_VAN_SIR` VARCHAR(30),
  `EC` VARCHAR(30),
  `Cot` VARCHAR(30),
  `Tet__autocolour` VARCHAR(30),
  `FQ__autocolour` VARCHAR(30),
  `Other` VARCHAR(30),
  `PBP1A_2B_2X__autocolour` VARCHAR(30),
  `WGS_PEN_SIR_Meningitis__colour` VARCHAR(30),
  `WGS_PEN_SIR_Nonmeningitis__colour` VARCHAR(30),
  `WGS_AMO_SIR__colour` VARCHAR(30),
  `WGS_MER_SIR__colour` VARCHAR(30),
  `WGS_TAX_SIR_Meningitis__colour` VARCHAR(30),
  `WGS_TAX_SIR_Nonmeningitis__colour` VARCHAR(30),
  `WGS_CFT_SIR_Meningitis__colour` VARCHAR(30),
  `WGS_CFT_SIR_Nonmeningitis__colour` VARCHAR(30),
  `WGS_CFX_SIR__colour` VARCHAR(30),
  `WGS_ERY_SIR__colour` VARCHAR(30),
  `WGS_CLI_SIR__colour` VARCHAR(30),
  `WGS_SYN_SIR__colour` VARCHAR(30),
  `WGS_LZO_SIR__colour` VARCHAR(30),
  `WGS_COT_SIR__colour` VARCHAR(30),
  `WGS_TET_SIR__colour` VARCHAR(30),
  `WGS_DOX_SIR__colour` VARCHAR(30),
  `WGS_LFX_SIR__colour` VARCHAR(30),
  `WGS_CHL_SIR__colour` VARCHAR(30),
  `WGS_RIF_SIR__colour` VARCHAR(30),
  `WGS_VAN_SIR__colour` VARCHAR(30),
  `ermB` VARCHAR(30),
  `ermB__colour` VARCHAR(30),
  `mefA` VARCHAR(30),
  `mefA__colour` VARCHAR(30),
  `folA_I100L` VARCHAR(30),
  `folA_I100L__colour` VARCHAR(30),
  `folP__autocolour` VARCHAR(30),
  `cat` VARCHAR(30),
  `cat__colour` VARCHAR(30),
  `PCV7` VARCHAR(30),
  `PCV10` VARCHAR(30),
  `PCV13` VARCHAR(30),
  `PCV15` VARCHAR(30),
  `PCV20` VARCHAR(30),
  `Pneumosil` VARCHAR(30),
  `Published` VARCHAR(30),
  PRIMARY KEY (`lane_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- gps_qc_data table

DROP TABLE IF EXISTS `gps_qc_data`;

CREATE TABLE IF NOT EXISTS `gps_qc_data` (
  `lane_id` VARCHAR(256) NOT NULL,
  `sample_name` VARCHAR(256) NOT NULL,
  `sample_accession` VARCHAR(256) NOT NULL,
  `lane_accession` VARCHAR(256) NOT NULL,
  `supplier_name` VARCHAR(256) NOT NULL,
  `public_name` VARCHAR(256) NOT NULL,
  `Streptococcus_pneumoniae` DECIMAL(5,2) CHECK (Streptococcus_pneumoniae>=0 AND Streptococcus_pneumoniae<=100),
  `total_length` INT(11),
  `No_contigs` INT(11),
  `genome_covered` DECIMAL(5,2) CHECK (genome_covered>=0 AND genome_covered<=100),
  `depth_of_coverage` DECIMAL(6,2) CHECK (depth_of_coverage>=0 AND depth_of_coverage<=2000),
  `X_Het_SNPs_Total_No_of_SNPs` VARCHAR(30),
  `qc` VARCHAR(30),
  `Hetsites_50bp` VARCHAR(30),
PRIMARY KEY (`lane_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Update the database version
CALL update_database_version('0.3.3', 'Regenerate all gps tables using updated schemas');

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;