# **************************************************************
# Update v 3.4 GPS schema
# **************************************************************

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- The gps_in_silico table.

DROP TABLE IF EXISTS `gps_in_silico`;

CREATE TABLE IF NOT EXISTS `gps_in_silico` (
  # THIS TABLE DEFINITION IS AUTO-GENERATED BY update_config_files.py, DO NOT EDIT MANUALLY!
  `lane_id` VARCHAR(256) NOT NULL,
  `sample` VARCHAR(256) NOT NULL,
  `public_name` VARCHAR(256) NOT NULL,
  `ERR` VARCHAR(256),
  `ERS` VARCHAR(256),
  `no_of_genome` SMALLINT(6) DEFAULT NULL,
  `duplicate` VARCHAR(30),
  `Paper_1` VARCHAR(30),
  `In_Silico_St` VARCHAR(20) NOT NULL,
  `aroE` VARCHAR(30),
  `gdh` VARCHAR(30),
  `gki` VARCHAR(30),
  `recP` VARCHAR(30),
  `spi` VARCHAR(30),
  `xpt` VARCHAR(30),
  `ddl` VARCHAR(30),
  `country` VARCHAR(256),
  `Continent` VARCHAR(256),
  `Manifest_type` VARCHAR(30),
  `children_under_5yrs` VARCHAR(30),
  `GPSC` SMALLINT(4),
  `GPSC__colour` VARCHAR(30),
  `In_silico_serotype` VARCHAR(30),
  `In_silico_serotype__colour` VARCHAR(30),
  `pbp1a` VARCHAR(30),
  `pbp2b` VARCHAR(30),
  `pbp2x` VARCHAR(30),
  `WGS_PEN` VARCHAR(30),
  `WGS_PEN_SIR_Meningitis` VARCHAR(30),
  `WGS_PEN_SIR_Nonmeningitis` VARCHAR(30),
  `WGS_AMO` VARCHAR(30),
  `WGS_AMO_SIR` VARCHAR(30),
  `WGS_MER` VARCHAR(30),
  `WGS_MER_SIR` VARCHAR(30),
  `WGS_TAX` VARCHAR(30),
  `WGS_TAX_SIR_Meningitis` VARCHAR(30),
  `WGS_TAX_SIR_Nonmeningitis` VARCHAR(30),
  `WGS_CFT` VARCHAR(30),
  `WGS_CFT_SIR_Meningitis` VARCHAR(30),
  `WGS_CFT_SIR_Nonmeningitis` VARCHAR(30),
  `WGS_CFX` VARCHAR(30),
  `WGS_CFX_SIR` VARCHAR(30),
  `WGS_ERY` VARCHAR(30),
  `WGS_ERY_SIR` VARCHAR(30),
  `WGS_CLI` VARCHAR(30),
  `WGS_CLI_SIR` VARCHAR(30),
  `WGS_SYN` VARCHAR(30),
  `WGS_SYN_SIR` VARCHAR(30),
  `WGS_LZO` VARCHAR(30),
  `WGS_LZO_SIR` VARCHAR(30),
  `WGS_ERY_CLI` VARCHAR(30),
  `WGS_COT` VARCHAR(30),
  `WGS_COT_SIR` VARCHAR(30),
  `WGS_TET` VARCHAR(30),
  `WGS_TET_SIR` VARCHAR(30),
  `WGS_DOX` VARCHAR(30),
  `WGS_DOX_SIR` VARCHAR(30),
  `WGS_LFX` VARCHAR(30),
  `WGS_LFX_SIR` VARCHAR(30),
  `WGS_CHL` VARCHAR(30),
  `WGS_CHL_SIR` VARCHAR(30),
  `WGS_RIF` VARCHAR(30),
  `WGS_RIF_SIR` VARCHAR(30),
  `WGS_VAN` VARCHAR(30),
  `WGS_VAN_SIR` VARCHAR(30),
  `EC` VARCHAR(30),
  `Cot` VARCHAR(100),
  `Tet__autocolour` VARCHAR(30),
  `FQ__autocolour` VARCHAR(400),
  `Other` VARCHAR(256),
  `PBP1A_2B_2X__autocolour` VARCHAR(30),
  `WGS_PEN_SIR_Meningitis__colour` VARCHAR(30),
  `WGS_PEN_SIR_Nonmeningitis__colour` VARCHAR(30),
  `WGS_AMO_SIR__colour` VARCHAR(30),
  `WGS_MER_SIR__colour` VARCHAR(30),
  `WGS_TAX_SIR_Meningitis__colour` VARCHAR(30),
  `WGS_TAX_SIR_Nonmeningitis__colour` VARCHAR(30),
  `WGS_CFT_SIR_Meningitis__colour` VARCHAR(30),
  `WGS_CFT_SIR_Nonmeningitis__colour` VARCHAR(30),
  `WGS_CFX_SIR__colour` VARCHAR(30),
  `WGS_ERY_SIR__colour` VARCHAR(30),
  `WGS_CLI_SIR__colour` VARCHAR(30),
  `WGS_SYN_SIR__colour` VARCHAR(30),
  `WGS_LZO_SIR__colour` VARCHAR(30),
  `WGS_COT_SIR__colour` VARCHAR(30),
  `WGS_TET_SIR__colour` VARCHAR(30),
  `WGS_DOX_SIR__colour` VARCHAR(30),
  `WGS_LFX_SIR__colour` VARCHAR(30),
  `WGS_CHL_SIR__colour` VARCHAR(30),
  `WGS_RIF_SIR__colour` VARCHAR(30),
  `WGS_VAN_SIR__colour` VARCHAR(30),
  `ermB` VARCHAR(30),
  `ermB__colour` VARCHAR(30),
  `mefA` VARCHAR(30),
  `mefA__colour` VARCHAR(30),
  `folA_I100L` VARCHAR(30),
  `folA_I100L__colour` VARCHAR(30),
  `folP__autocolour` VARCHAR(30),
  `cat` VARCHAR(30),
  `cat__colour` VARCHAR(30),
  `PCV7` VARCHAR(30),
  `PCV10` VARCHAR(30),
  `PCV13` VARCHAR(30),
  `PCV15` VARCHAR(30),
  `PCV20` VARCHAR(30),
  `Pneumosil` VARCHAR(30),
  `Published` VARCHAR(30),
  # END OF AUTO_GENERATED SECTION
  PRIMARY KEY (`lane_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- The gps_qc_data table.

DROP TABLE IF EXISTS `gps_qc_data`;

CREATE TABLE IF NOT EXISTS `gps_qc_data` (
  # THIS TABLE DEFINITION IS AUTO-GENERATED BY update_config_files.py, DO NOT EDIT MANUALLY!
  `lane_id` VARCHAR(256) NOT NULL,
  `Streptococcus_pneumoniae` DECIMAL(5,2) CHECK (Streptococcus_pneumoniae>=0 AND Streptococcus_pneumoniae<=100),
  `total_length` INT(10),
  `No_contigs` SMALLINT(5),
  `genome_covered` DECIMAL(5,2) CHECK (genome_covered>=0 AND genome_covered<=100),
  `depth_of_coverage` DECIMAL(6,2) CHECK (depth_of_coverage>=0 AND depth_of_coverage<=2000),
  `Proportion_of_Het_SNPs` DECIMAL(5,2) CHECK (Proportion_of_Het_SNPs>=0 AND Proportion_of_Het_SNPs<=100),
  `qc` VARCHAR(30),
  `supplier_name` VARCHAR(256) NOT NULL,
  `Hetsites_50bp` SMALLINT(4),
  # END OF AUTO_GENERATED SECTION
PRIMARY KEY (`lane_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Update the database version
CALL update_database_version('0.7.3', 'Update v 3.4 GPS schema');


/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
