# **************************************************************
# The gps_sample table.
# **************************************************************

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `gps_sample`;

CREATE TABLE `gps_sample` (
  # THIS TABLE DEFINITION IS AUTO-GENERATED BY update_config_files.py, DO NOT EDIT MANUALLY!
  `sample_name` VARCHAR(256) NOT NULL,
  `sanger_sample_id` VARCHAR(256) NOT NULL,
  `public_name` VARCHAR(256) NOT NULL,
  `study_name` VARCHAR(600),
  `submitting_institution_key` VARCHAR(256) NOT NULL,
  `selection_random` VARCHAR(10) DEFAULT NULL,
  `country` VARCHAR(90),
  `region` VARCHAR(90),
  `city` VARCHAR(200),
  `facility_where_collected` VARCHAR(256) DEFAULT NULL,
  `month_collection` VARCHAR(10) DEFAULT NULL,
  `year_collection` INT(11) DEFAULT NULL,
  `gender` VARCHAR(10) DEFAULT NULL,
  `age_years` INT(11) DEFAULT NULL,
  `age_months` INT(11) DEFAULT NULL,
  `age_days` INT(11) DEFAULT NULL,
  `clinical_manifestation` VARCHAR(256),
  `source` VARCHAR(100),
  `HIV_status` VARCHAR(10),
  `underlying_conditions` VARCHAR(256),
  `phenotypic_serotype_method` VARCHAR(100),
  `phenotypic_serotype` VARCHAR(100),
  `sequence_type` VARCHAR(256),
  `penicillin` VARCHAR(30),
  `AST_method_penicillin` VARCHAR(60),
  `amoxicillin` VARCHAR(30),
  `AST_method_amoxicillin` VARCHAR(60),
  `cefotaxime` VARCHAR(30),
  `AST_method_cefotaxime` VARCHAR(60),
  `ceftriaxone` VARCHAR(30),
  `AST_method_ceftriaxone` VARCHAR(60),
  `cefuroxime` VARCHAR(30),
  `AST_method_cefuroxime` VARCHAR(60),
  `Meropenem` VARCHAR(30),
  `AST_method_meropenem` VARCHAR(60),
  `erythromycin` VARCHAR(30),
  `AST_method_erythromycin` VARCHAR(60),
  `clindamycin` VARCHAR(30),
  `AST_method_clindamycin` VARCHAR(60),
  `trim_sulfa` VARCHAR(30),
  `AST_method_trim_sulfa` VARCHAR(60),
  `vancomycin` VARCHAR(30),
  `AST_method_vancomycin` VARCHAR(60),
  `linezolid` VARCHAR(30),
  `AST_method_linezolid` VARCHAR(60),
  `ciprofloxacin` VARCHAR(30),
  `AST_method_ciprofloxacin` VARCHAR(60),
  `chloramphenicol` VARCHAR(30),
  `AST_method_chloramphenicol` VARCHAR(60),
  `tetracycline` VARCHAR(30),
  `AST_method_tetracycline` VARCHAR(60),
  `levofloxacin` VARCHAR(30),
  `AST_method_levofloxacin` VARCHAR(60),
  `synercid` VARCHAR(30),
  `AST_method_synercid` VARCHAR(60),
  `rifampin` VARCHAR(30),
  `AST_method_rifampin` VARCHAR(60),
  `aroe` VARCHAR(100),
  `gdh` VARCHAR(100),
  `gki` VARCHAR(100),
  `recp` VARCHAR(100),
  `spi` VARCHAR(100),
  `xpt` VARCHAR(100),
  `ddl` VARCHAR(100),
  `comments` VARCHAR(256),
  `vaccine_period` VARCHAR(200),
  `intro_year` SMALLINT(6) DEFAULT NULL,
  `PCV_type` VARCHAR(100),
  `resolution` SMALLINT(4),
  # END OF AUTO_GENERATED SECTION
  PRIMARY KEY (`public_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
