# **************************************************************
# The gps_qc_data table.
# **************************************************************

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `gps_qc_data`;

CREATE TABLE IF NOT EXISTS `gps_qc_data` (
  # THIS TABLE DEFINITION IS AUTO-GENERATED BY update_config_files.py, DO NOT EDIT MANUALLY!
  `lane_id` VARCHAR(256) NOT NULL,
  `Streptococcus_pneumoniae` DECIMAL(5,2) CHECK (Streptococcus_pneumoniae>=0 AND Streptococcus_pneumoniae<=100),
  `total_length` DECIMAL(5,2) CHECK (total_length>=0 AND total_length<=100),
  `No_contigs` SMALLINT(5),
  `genome_covered` DECIMAL(5,2) CHECK (genome_covered>=0 AND genome_covered<=100),
  `depth_of_coverage` DECIMAL(6,2) CHECK (depth_of_coverage>=0 AND depth_of_coverage<=2000),
  `Proportion_of_Het_SNPs` DECIMAL(5,2) CHECK (Proportion_of_Het_SNPs>=0 AND Proportion_of_Het_SNPs<=100),
  `qc` VARCHAR(30),
  `supplier_name` VARCHAR(256) NOT NULL,
  `Hetsites_50bp` SMALLINT(4),
  # END OF AUTO_GENERATED SECTION
PRIMARY KEY (`lane_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
