FROM python:3-slim

ARG VERSION='VERSION'
ENV VERSION=$VERSION

WORKDIR /app

# install (separation of COPY to help cache dependencies)
COPY Pipfile Pipfile.lock /app/
RUN pip install pipenv \
    && pipenv install --system --ignore-pipfile

# add rest of code
COPY . /app

RUN python manage.py migrate \
    && python manage.py loaddev \
    && python manage.py collectstatic

EXPOSE 8000